import type { ContextBundle } from '@co-reader/shared';
import { db,now,row, rows } from '../db/index.js';

const tokens=(text:string)=>Math.ceil(text.length/4);
export function buildContext(documentVersionId:string,profile:string,anchorId?:string,threadId?:string,window=128000):ContextBundle {
  const version=row<{canonical_text:string}>('SELECT canonical_text FROM document_versions WHERE id=?',documentVersionId);if(!version)throw new Error('Document version not found');
  const anchor=anchorId?row<{exact_quote:string;block_id:string;block_text:string}>('SELECT a.exact_quote,a.block_id,b.text_content block_text FROM anchors a JOIN blocks b ON b.id=a.block_id AND b.document_version_id=a.document_version_id WHERE a.id=?',anchorId):undefined;
  const neighbor=anchor?{text_content:rows<{text_content:string}>('SELECT text_content FROM blocks WHERE document_version_id=? AND ordinal BETWEEN (SELECT ordinal-1 FROM blocks WHERE id=? AND document_version_id=?) AND (SELECT ordinal+1 FROM blocks WHERE id=? AND document_version_id=?) ORDER BY ordinal',documentVersionId,anchor.block_id,documentVersionId,anchor.block_id,documentVersionId).map(item=>item.text_content).join('\n')}:undefined;
  const branch=threadId?activeBranch(threadId):[];
  const notes=rows<{note:string;exact_quote:string}>(`SELECT h.note,a.exact_quote FROM highlights h JOIN anchors a ON a.id=h.anchor_id WHERE a.document_version_id=? AND h.checked=1`,documentVersionId).map(n=>n.note||n.exact_quote);
  if(tokens(version.canonical_text)<1200)return {tier:'canonical',article:version.canonical_text,...(anchor?{anchor:anchor.exact_quote||anchor.block_text}:{}),...(neighbor?{neighboringBlock:neighbor.text_content}:{}),branch,curatedNotes:notes,tokenEstimate:tokens(version.canonical_text)+tokens(JSON.stringify(branch))};
  const full=tokens(version.canonical_text)+tokens(JSON.stringify(branch))+4000;
  if(['deep','vision','research'].includes(profile)&&full<=window)return {tier:'canonical',article:version.canonical_text,...(anchor?{anchor:anchor.exact_quote||anchor.block_text}:{}),branch,curatedNotes:notes,tokenEstimate:full};
  const tier=profile==='quick'?'brief':'study';const cached=row<{content:string;token_estimate:number}>('SELECT content,token_estimate FROM context_cache WHERE document_version_id=? AND tier=?',documentVersionId,tier);
  const maximum=tier==='brief'?Math.min(12000,Math.floor(version.canonical_text.length*.25)):Math.min(48000,Math.floor(version.canonical_text.length*.6));
  const article=cached?.content??version.canonical_text.slice(0,maximum);
  const contextualBranch=full>window&&threadId?[{role:'assistant' as const,content:branchDigest(threadId,branch)}]:branch;
  return {tier:full>window?'study-with-branch-digest':tier,article,...(anchor?{anchor:anchor.exact_quote||anchor.block_text}:{}),...(neighbor?{neighboringBlock:neighbor.text_content}:{}),branch:contextualBranch,curatedNotes:notes,tokenEstimate:(cached?.token_estimate??tokens(article))+tokens(JSON.stringify(contextualBranch))};
}
function activeBranch(threadId:string):Array<{role:'user'|'assistant';content:string}>{const segments:Array<Array<{role:'user'|'assistant';content:string}>>=[];let current:string|undefined=threadId,cutoff:string|undefined,limit=32;while(current&&limit-->0){const thread:{parent_message_id:string|null}|undefined=row<{parent_message_id:string|null}>('SELECT parent_message_id FROM threads WHERE id=?',current);if(!thread)break;segments.unshift(cutoff?rows<{role:'user'|'assistant';content:string}>('SELECT role,content FROM messages WHERE thread_id=? AND created_at<=(SELECT created_at FROM messages WHERE id=?) ORDER BY created_at',current,cutoff):rows<{role:'user'|'assistant';content:string}>('SELECT role,content FROM messages WHERE thread_id=? ORDER BY created_at',current));if(!thread.parent_message_id)break;const parent:{thread_id:string}|undefined=row<{thread_id:string}>('SELECT thread_id FROM messages WHERE id=?',thread.parent_message_id);cutoff=thread.parent_message_id;current=parent?.thread_id}return segments.flat()}
function branchDigest(threadId:string,branch:Array<{role:'user'|'assistant';content:string}>):string{const cached=row<{version:number;message_count:number;content:string}>('SELECT version,message_count,content FROM branch_digests WHERE thread_id=? ORDER BY version DESC LIMIT 1',threadId);if(cached?.message_count===branch.length)return `[Branch digest v${cached.version}]\n${cached.content}`;const content=branch.map((message,index)=>`${index+1}. ${message.role}: ${message.content.slice(0,index===branch.length-1?2000:600)}`).join('\n'),version=(cached?.version??0)+1;db.prepare('INSERT INTO branch_digests(thread_id,version,message_count,content,created_at)VALUES(?,?,?,?,?)').run(threadId,version,branch.length,content,now());return `[Branch digest v${version}]\n${content}`}
