import type { ContextBundle, ReaderSignal } from '@profread/shared';
import { db,now,row, rows } from '../db/index.js';
import { contextBehaviorSettings } from './behavior.js';

const tokens=(text:string)=>Math.ceil(text.length/4);
const signalLabels:Record<ReaderSignal['kind'],string>={important:'IMPORTANT',comment:'READER COMMENT',question:'OPEN QUESTION'};
export function formatReaderSignal(signal:ReaderSignal):string {
  const quote=signal.exactQuote.replace(/\s+/g,' ').trim(),note=signal.note?.replace(/\s+/g,' ').trim();
  return `[${signalLabels[signal.kind]}] "${quote}"${note?` — ${note}`:''}`;
}
export function buildContext(documentVersionId:string,profile:string,anchorId?:string,threadId?:string,window=128000):ContextBundle {
  const settings=contextBehaviorSettings();
  const version=row<{canonical_text:string}>('SELECT canonical_text FROM document_versions WHERE id=?',documentVersionId);if(!version)throw new Error('Document version not found');
  const anchor=anchorId?row<{exact_quote:string;block_id:string;block_text:string}>('SELECT a.exact_quote,a.block_id,b.text_content block_text FROM anchors a JOIN blocks b ON b.id=a.block_id AND b.document_version_id=a.document_version_id WHERE a.id=?',anchorId):undefined;
  const neighbor=anchor?{text_content:rows<{text_content:string}>('SELECT text_content FROM blocks WHERE document_version_id=? AND ordinal BETWEEN (SELECT ordinal-1 FROM blocks WHERE id=? AND document_version_id=?) AND (SELECT ordinal+1 FROM blocks WHERE id=? AND document_version_id=?) ORDER BY ordinal',documentVersionId,anchor.block_id,documentVersionId,anchor.block_id,documentVersionId).map(item=>item.text_content).join('\n')}:undefined;
  const branch=threadId?activeBranch(threadId,settings.threadAncestorLimit):[];
  const readerSignals=rows<{id:string;kind:string;note:string|null;exact_quote:string}>(`SELECT h.id,h.kind,h.note,a.exact_quote FROM highlights h JOIN anchors a ON a.id=h.anchor_id WHERE a.document_version_id=? AND (a.representation_id IS NULL OR a.representation_id IN (SELECT id FROM document_representations WHERE kind='html')) ORDER BY a.start_offset,h.created_at`,documentVersionId).map(item=>({id:item.id,kind:(['important','question','comment'].includes(item.kind)?item.kind:'important') as ReaderSignal['kind'],exactQuote:item.exact_quote,note:item.note}));
  const notes=readerSignals.map(formatReaderSignal),signalTokens=tokens(notes.join('\n')),branchTokens=tokens(JSON.stringify(branch));
  if(tokens(version.canonical_text)<settings.fullArticleThresholdTokens)return {tier:'canonical',article:version.canonical_text,...(anchor?{anchor:anchor.exact_quote||anchor.block_text}:{}),...(neighbor?{neighboringBlock:neighbor.text_content}:{}),branch,readerSignals,curatedNotes:notes,tokenEstimate:tokens(version.canonical_text)+branchTokens+signalTokens};
  const full=tokens(version.canonical_text)+branchTokens+signalTokens+settings.reservedPromptTokens;
  if(['deep','vision','research'].includes(profile)&&full<=window)return {tier:'canonical',article:version.canonical_text,...(anchor?{anchor:anchor.exact_quote||anchor.block_text}:{}),branch,readerSignals,curatedNotes:notes,tokenEstimate:full};
  const tier=profile==='quick'?'brief':'study';const cached=row<{content:string;token_estimate:number}>('SELECT content,token_estimate FROM context_cache WHERE document_version_id=? AND tier=?',documentVersionId,tier);
  const maximum=tier==='brief'?Math.min(settings.quickContextMaxTokens*4,Math.floor(version.canonical_text.length*settings.quickContextPercent/100)):Math.min(settings.studyContextMaxTokens*4,Math.floor(version.canonical_text.length*settings.studyContextPercent/100));
  const article=cached?.content??version.canonical_text.slice(0,maximum);
  const contextualBranch=full>window&&threadId?[{role:'assistant' as const,content:branchDigest(threadId,branch,settings.digestOlderMessageCharacters,settings.digestLatestMessageCharacters)}]:branch;
  return {tier:full>window?'study-with-branch-digest':tier,article,...(anchor?{anchor:anchor.exact_quote||anchor.block_text}:{}),...(neighbor?{neighboringBlock:neighbor.text_content}:{}),branch:contextualBranch,readerSignals,curatedNotes:notes,tokenEstimate:(cached?.token_estimate??tokens(article))+tokens(JSON.stringify(contextualBranch))+signalTokens};
}
function activeBranch(threadId:string,ancestorLimit:number):Array<{role:'user'|'assistant';content:string}>{const segments:Array<Array<{role:'user'|'assistant';content:string}>>=[];let current:string|undefined=threadId,cutoff:string|undefined,limit=ancestorLimit;while(current&&limit-->0){const thread:{parent_message_id:string|null}|undefined=row<{parent_message_id:string|null}>('SELECT parent_message_id FROM threads WHERE id=?',current);if(!thread)break;segments.unshift(cutoff?rows<{role:'user'|'assistant';content:string}>('SELECT role,content FROM messages WHERE thread_id=? AND created_at<=(SELECT created_at FROM messages WHERE id=?) ORDER BY created_at',current,cutoff):rows<{role:'user'|'assistant';content:string}>('SELECT role,content FROM messages WHERE thread_id=? ORDER BY created_at',current));if(!thread.parent_message_id)break;const parent:{thread_id:string}|undefined=row<{thread_id:string}>('SELECT thread_id FROM messages WHERE id=?',thread.parent_message_id);cutoff=thread.parent_message_id;current=parent?.thread_id}return segments.flat()}
function branchDigest(threadId:string,branch:Array<{role:'user'|'assistant';content:string}>,olderCharacters:number,latestCharacters:number):string{const cached=row<{version:number;message_count:number;content:string}>('SELECT version,message_count,content FROM branch_digests WHERE thread_id=? ORDER BY version DESC LIMIT 1',threadId);if(cached?.message_count===branch.length)return `[Branch digest v${cached.version}]\n${cached.content}`;const content=branch.map((message,index)=>`${index+1}. ${message.role}: ${message.content.slice(0,index===branch.length-1?latestCharacters:olderCharacters)}`).join('\n'),version=(cached?.version??0)+1;db.prepare('INSERT INTO branch_digests(thread_id,version,message_count,content,created_at)VALUES(?,?,?,?,?)').run(threadId,version,branch.length,content,now());return `[Branch digest v${version}]\n${content}`}
