import type { ModelDefinition, ModelProvider, ProviderRunRequest, RunEvent } from '@co-reader/shared';

async function* sse(response: Response): AsyncIterable<{event?:string;data:string}> {
  if(!response.ok)throw new Error(`Provider returned ${response.status}: ${await response.text()}`);
  if(!response.body)throw new Error('Provider response has no body'); const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
  while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});const chunks=buffer.split(/\r?\n\r?\n/);buffer=chunks.pop()??'';for(const chunk of chunks){let event:string|undefined;const data:string[]=[];for(const line of chunk.split(/\r?\n/)){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data.push(line.slice(5).trimStart());}if(data.length)yield {...(event?{event}:{}),data:data.join('\n')};}if(done)break;}
}
const authHeaders=(key:string)=>({'content-type':'application/json','authorization':`Bearer ${key}`});
export class ResponsesProvider implements ModelProvider {
  constructor(private readonly apiKey:string,private readonly models:ModelDefinition[],private readonly baseUrl='https://api.openai.com/v1'){}
  async listModels(){return this.models;} estimateContext(r:ProviderRunRequest){return Math.ceil(r.messages.reduce((n,m)=>n+m.content.length,0)/4);}
  async *run(request:ProviderRunRequest):AsyncIterable<RunEvent>{
    const input=request.messages.map((m,index)=>({role:m.role,content:[{type:m.role==='assistant'?'output_text':'input_text',text:m.content},...(request.image&&index===request.messages.length-1?[{type:'input_image',image_url:`data:${request.image.mimeType};base64,${request.image.data}`}]:[])]}));
    const body:Record<string,unknown>={model:request.model.id,input,stream:true,max_output_tokens:request.model.maxOutput,...(request.previousResponseId?{previous_response_id:request.previousResponseId}:{})};
    const tools:unknown[]=[];if(request.tools?.some(t=>t.name==='provider_web_search'))tools.push({type:'web_search_preview'});for(const tool of request.tools?.filter(t=>t.name!=='provider_web_search')??[])tools.push({type:'function',name:tool.name,parameters:tool.schema,strict:true});if(tools.length)body.tools=tools;
    const response=await fetch(`${this.baseUrl}/responses`,{method:'POST',headers:authHeaders(this.apiKey),body:JSON.stringify(body),...(request.signal?{signal:request.signal}:{})});
    for await(const item of sse(response)){if(item.data==='[DONE]')continue;const e=JSON.parse(item.data) as Record<string,any>;if(e.type==='response.output_text.delta')yield {type:'text_delta',delta:e.delta};else if(e.type==='response.output_item.done'&&e.item?.type==='function_call')yield {type:'tool_call',id:e.item.call_id??e.item.id,name:e.item.name,input:e.item.arguments};else if(e.type==='response.completed'){for(const output of e.response?.output??[])for(const content of output.content??[])for(const annotation of content.annotations??[])if(annotation.type==='url_citation'&&annotation.url)yield {type:'citation',citation:{id:crypto.randomUUID(),title:annotation.title,url:annotation.url,start:annotation.start_index,end:annotation.end_index}};const u=e.response?.usage; if(u)yield {type:'usage',inputTokens:u.input_tokens??0,outputTokens:u.output_tokens??0};yield {type:'completed',finishReason:e.response?.status??'completed',...(e.response?.id?{responseId:e.response.id}:{})};}else if(e.type==='response.failed')yield {type:'error',code:'provider_error',message:e.response?.error?.message??'Provider failed',retryable:true};}
  }
}
export class ChatCompletionsProvider implements ModelProvider {
  constructor(private readonly apiKey:string,private readonly models:ModelDefinition[],private readonly baseUrl:string,private readonly openRouter=false,private readonly routingControls?:Record<string,unknown>){}
  async listModels(){return this.models;} estimateContext(r:ProviderRunRequest){return Math.ceil(r.messages.reduce((n,m)=>n+m.content.length,0)/4);}
  async *run(request:ProviderRunRequest):AsyncIterable<RunEvent>{
    const messages=request.messages.map((m,index)=>request.image&&index===request.messages.length-1?{role:m.role,content:[{type:'text',text:m.content},{type:'image_url',image_url:{url:`data:${request.image.mimeType};base64,${request.image.data}`}}]}:m);const body:Record<string,unknown>={model:request.model.id,messages,stream:true,max_tokens:request.model.maxOutput,stream_options:{include_usage:true}};
    if(this.openRouter&&this.routingControls)body.provider=this.routingControls;if(request.tools?.some(t=>t.name==='provider_web_search')&&this.openRouter)body.plugins=[{id:'web'}];
    if(request.tools?.some(t=>t.name==='render_diagram'))body.tools=request.tools.filter(t=>t.name==='render_diagram').map(t=>({type:'function',function:{name:t.name,parameters:t.schema}}));
    const response=await fetch(`${this.baseUrl}/chat/completions`,{method:'POST',headers:{...authHeaders(this.apiKey),...(this.openRouter?{'HTTP-Referer':'https://co-reader.local','X-Title':'Co-reader'}:{})},body:JSON.stringify(body),...(request.signal?{signal:request.signal}:{})});
    const pendingTools=new Map<number,{id:string;name:string;arguments:string}>();let completed=false;for await(const item of sse(response)){if(item.data==='[DONE]'){if(!completed)yield {type:'completed',finishReason:'stop'};continue;}const e=JSON.parse(item.data) as Record<string,any>;const choice=e.choices?.[0],delta=choice?.delta;if(delta?.content)yield {type:'text_delta',delta:delta.content};for(const citation of e.citations??[])yield {type:'citation',citation:{id:crypto.randomUUID(),title:citation.title,url:citation.url}};for(const call of delta?.tool_calls??[]){const index=call.index??0,current=pendingTools.get(index)??{id:call.id??String(index),name:'',arguments:''};if(call.id)current.id=call.id;if(call.function?.name)current.name+=call.function.name;if(call.function?.arguments)current.arguments+=call.function.arguments;pendingTools.set(index,current)}if(e.usage)yield {type:'usage',inputTokens:e.usage.prompt_tokens??0,outputTokens:e.usage.completion_tokens??0};if(choice?.finish_reason){for(const tool of pendingTools.values())yield {type:'tool_call',id:tool.id,name:tool.name,input:tool.arguments};pendingTools.clear();completed=true;yield {type:'completed',finishReason:choice.finish_reason};}}
  }
}
