import { capabilitySchema, modelDefinitionSchema, modelProfileSchema, type ModelDefinition, type ModelProfile } from '@co-reader/shared';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { db, row, rows } from '../db/index.js';

export function seedModelSettings():void {
  if(!row('SELECT id FROM model_settings LIMIT 1')){
    db.prepare('INSERT INTO model_settings (id,provider_id,label,protocol,base_url,secret_env_name,config_json) VALUES (?,?,?,?,?,?,?)').run('openai','openai','OpenAI','openai-responses','https://api.openai.com/v1','OPENAI_API_KEY','{}');
    db.prepare('INSERT INTO model_settings (id,provider_id,label,protocol,base_url,secret_env_name,config_json) VALUES (?,?,?,?,?,?,?)').run('openrouter','openrouter','OpenRouter','openrouter','https://openrouter.ai/api/v1','OPENROUTER_API_KEY','{}');
    const insert=db.prepare('INSERT INTO model_definitions (id,provider_id,label,protocol,context_window,max_output,capabilities_json,priority) VALUES (?,?,?,?,?,?,?,?)');
    insert.run('gpt-4.1-mini','openai','OpenAI quick','openai-responses',1047576,16384,JSON.stringify({text:true,vision:true,structuredOutput:true,functionTools:true,providerWebSearch:true,reasoningControl:false,streaming:true}),10);
    insert.run('gpt-4.1','openai','OpenAI deep','openai-responses',1047576,32768,JSON.stringify({text:true,vision:true,structuredOutput:true,functionTools:true,providerWebSearch:true,reasoningControl:false,streaming:true}),20);
    for(const [name,ids] of [['quick',['gpt-4.1-mini']],['standard',['gpt-4.1-mini']],['deep',['gpt-4.1']],['vision',['gpt-4.1']],['research',['gpt-4.1']],['digest',['gpt-4.1']]] as const)db.prepare('INSERT INTO model_profiles (name,model_ids_json) VALUES (?,?)').run(name,JSON.stringify(ids));
  }
}
export function models():ModelDefinition[]{return rows<Record<string,unknown>>('SELECT * FROM model_definitions WHERE enabled=1').map(m=>modelDefinitionSchema.parse({id:m.id,providerId:m.provider_id,label:m.label,protocol:m.protocol,contextWindow:m.context_window,maxOutput:m.max_output,capabilities:JSON.parse(m.capabilities_json as string),priority:m.priority,enabled:Boolean(m.enabled)}));}
export function profiles():ModelProfile[]{return rows<{name:string;model_ids_json:string}>('SELECT * FROM model_profiles').map(p=>modelProfileSchema.parse({name:p.name,modelIds:JSON.parse(p.model_ids_json)}));}
export function registerSettingsRoutes(app:FastifyInstance):void {
  app.get('/api/settings/models',async()=>({providers:rows(`SELECT id,provider_id,label,protocol,base_url,secret_env_name,config_json,enabled FROM model_settings`),models:models(),profiles:profiles()}));
  app.put('/api/settings/providers/:id',async(request,reply)=>{const parsed=z.object({label:z.string().min(1),protocol:z.enum(['openai-responses','chat-completions','openrouter']),baseUrl:z.string().url(),secretEnvName:z.string().regex(/^[A-Z][A-Z0-9_]*$/),enabled:z.boolean(),config:z.record(z.string(),z.unknown()).default({})}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});const id=(request.params as {id:string}).id;db.prepare(`INSERT INTO model_settings(id,provider_id,label,protocol,base_url,secret_env_name,config_json,enabled) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET label=excluded.label,protocol=excluded.protocol,base_url=excluded.base_url,secret_env_name=excluded.secret_env_name,config_json=excluded.config_json,enabled=excluded.enabled`).run(id,id,parsed.data.label,parsed.data.protocol,parsed.data.baseUrl,parsed.data.secretEnvName,JSON.stringify(parsed.data.config),parsed.data.enabled?1:0);return {ok:true};});
  app.put('/api/settings/models/:id',async(request,reply)=>{const input={...(request.body as object),id:(request.params as {id:string}).id};const parsed=modelDefinitionSchema.safeParse(input);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});const m=parsed.data;db.prepare(`INSERT INTO model_definitions(id,provider_id,label,protocol,context_window,max_output,capabilities_json,priority,enabled) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET provider_id=excluded.provider_id,label=excluded.label,protocol=excluded.protocol,context_window=excluded.context_window,max_output=excluded.max_output,capabilities_json=excluded.capabilities_json,priority=excluded.priority,enabled=excluded.enabled`).run(m.id,m.providerId,m.label,m.protocol,m.contextWindow,m.maxOutput,JSON.stringify(capabilitySchema.parse(m.capabilities)),m.priority,m.enabled?1:0);return {ok:true};});
  app.put('/api/settings/profiles/:name',async(request,reply)=>{const parsed=modelProfileSchema.safeParse({...(request.body as object),name:(request.params as {name:string}).name});if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});db.prepare(`INSERT INTO model_profiles(name,model_ids_json) VALUES(?,?) ON CONFLICT(name) DO UPDATE SET model_ids_json=excluded.model_ids_json`).run(parsed.data.name,JSON.stringify(parsed.data.modelIds));return {ok:true};});
  app.get('/api/settings/providers/:id/catalog',async(request,reply)=>{const setting=providerSetting((request.params as {id:string}).id);if(!setting||setting.protocol!=='openrouter')return reply.code(422).send({error:'Catalog discovery is available for OpenRouter providers'});const key=process.env[setting.secret_env_name];if(!key)return reply.code(422).send({error:`Server secret ${setting.secret_env_name} is not configured`});const response=await fetch(`${setting.base_url}/models`,{headers:{authorization:`Bearer ${key}`}});if(!response.ok)return reply.code(502).send({error:`Catalog returned ${response.status}`});const result=await response.json() as {data?:Array<{id:string;name?:string;context_length?:number;architecture?:unknown;pricing?:unknown}>};return(result.data??[]).map(model=>({id:model.id,label:model.name??model.id,contextWindow:model.context_length??0,architecture:model.architecture,pricing:model.pricing}));});
}
export function providerSetting(providerId:string){return row<{protocol:string;base_url:string;secret_env_name:string;config_json:string;enabled:number}>('SELECT protocol,base_url,secret_env_name,config_json,enabled FROM model_settings WHERE provider_id=?',providerId);}
