import { createHash } from 'node:crypto';
import * as cheerio from 'cheerio';
import sanitizeHtml from 'sanitize-html';

export interface SanitizedDocument {
  html: string; title: string; canonicalText: string;
  blocks: Array<{ id: string; ordinal: number; type: string; text: string; visual?: string; start: number; end: number }>;
}

const blockSelector = 'h1,h2,h3,h4,h5,h6,p,li,blockquote,pre,figcaption,table,img,svg,figure,video';
const allowedTags = sanitizeHtml.defaults.allowedTags.concat(['html','head','body','link','main','article','section','figure','figcaption','picture','img','video','source','iframe','svg','path','g','circle','rect','line','polyline','polygon','ellipse','text','defs','use','symbol','table','thead','tbody','tfoot','tr','th','td','colgroup','col','details','summary']);
const allowedAttributes: sanitizeHtml.IOptions['allowedAttributes'] = {
  '*': ['id','class','title','aria-label','aria-describedby','role','data-*'],
  a: ['href','name','target','rel'], img: ['src','alt','width','height','srcset'], video: ['controls','width','height','aria-label'], source: ['src','srcset','type','media'],
  iframe: ['src','title','width','height','allow','allowfullscreen','loading','referrerpolicy'],
  link: ['href','rel','media'],
  svg: ['viewBox','width','height','xmlns','fill','stroke','aria-label','role'],
  path: ['d','fill','stroke','stroke-width'], g: ['transform','fill','stroke'], circle: ['cx','cy','r','fill','stroke'],
  rect: ['x','y','rx','ry','width','height','fill','stroke'], line: ['x1','y1','x2','y2','stroke'],
  polyline: ['points','fill','stroke'], polygon: ['points','fill','stroke'], ellipse: ['cx','cy','rx','ry','fill','stroke'],
  text: ['x','y','dx','dy','text-anchor','font-size','fill'], use: ['href'], table: ['summary'], th: ['scope','colspan','rowspan'], td: ['colspan','rowspan'],
};

const remoteOrDangerous = /^(?:https?:|data:|javascript:|vbscript:|file:|\/\/)/i;
const embeddedImagePattern = /^data:(image\/(?:png|jpeg|gif|webp));base64,([a-z0-9+/=\s]+)$/i;
function safeEmbeddedImage(value:string):string|null{
  const match=value.match(embeddedImagePattern);if(!match)return null;
  const mime=match[1]!.toLowerCase(),payload=match[2]!.replace(/\s+/g,'');if(payload.length>12*1024*1024||payload.length%4===1)return null;
  const bytes=Buffer.from(payload,'base64'),canonical=bytes.toString('base64').replace(/=+$/,'');if(!bytes.length||bytes.length>8*1024*1024||canonical!==payload.replace(/=+$/,''))return null;
  const valid=mime==='image/png'?bytes.length>=8&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):mime==='image/jpeg'?bytes.length>=2&&bytes[0]===0xff&&bytes[1]===0xd8:mime==='image/gif'?bytes.length>=6&&['GIF87a','GIF89a'].includes(bytes.subarray(0,6).toString('ascii')):bytes.length>=12&&bytes.subarray(0,4).toString('ascii')==='RIFF'&&bytes.subarray(8,12).toString('ascii')==='WEBP';
  return valid?`data:${mime};base64,${payload}`:null;
}
function safeYoutubeEmbed(value:string):string|null{
  try{const url=new URL(value);if(url.protocol!=='https:'||!['youtube.com','www.youtube.com','youtube-nocookie.com','www.youtube-nocookie.com'].includes(url.hostname)||!/^\/embed\/[A-Za-z0-9_-]{6,}$/.test(url.pathname))return null;const safe=new URL(`https://www.youtube-nocookie.com${url.pathname}`);for(const key of ['start','autoplay','controls','rel','loop','mute','cc_lang_pref','cc_load_policy','hl'])if(url.searchParams.has(key))safe.searchParams.set(key,url.searchParams.get(key)!);return safe.toString()}catch{return null}
}
export function normalizeAssetPath(base: string, value: string): string | null {
  const clean = value.split(/[?#]/, 1)[0]?.replaceAll('\\', '/') ?? '';
  if (!clean || remoteOrDangerous.test(clean) || clean.startsWith('/')) return null;
  const segments = `${base}/${clean}`.split('/'); const result: string[] = [];
  for (const segment of segments) { if (!segment || segment === '.') continue; if (segment === '..') { if (!result.length) return null; result.pop(); } else result.push(segment); }
  return result.join('/');
}

function safeCss(css: string, rewrite: (path: string) => string | null): string {
  return css
    .replace(/@import[\s\S]*?(?:;|$)/gi, '')
    .replace(/expression\s*\([^)]*\)/gi, '')
    .replace(/url\(\s*(['"]?)(.*?)\1\s*\)/gi, (_all, _q, url: string) => { const safe = rewrite(url); return safe ? `url("${safe}")` : 'url("")'; });
}
export function sanitizeStylesheet(css:string,sourcePath:string,assetUrl:(path:string)=>string|null):string{const base=sourcePath.includes('/')?sourcePath.slice(0,sourcePath.lastIndexOf('/')):'';return safeCss(css,value=>{const path=normalizeAssetPath(base,value);return path?assetUrl(path):null})}

export function sanitizeDocument(source: string, entryPath: string, assetUrl: (path: string) => string | null): SanitizedDocument {
  const entryDir = entryPath.includes('/') ? entryPath.slice(0, entryPath.lastIndexOf('/')) : '';
  const $source = cheerio.load(source),sourceTitle=$source('title').first().text().replace(/\s+/g,' ').trim();
  const rewrite = (value: string): string | null => { const path = normalizeAssetPath(entryDir, value); return path ? assetUrl(path) : null; };
  let cleaned = sanitizeHtml(source, {
    allowedTags, allowedAttributes, allowedSchemes: [], allowedSchemesByTag:{img:['data'],iframe:['https']}, allowProtocolRelative: false,
    disallowedTagsMode: 'discard', nonTextTags: ['script','style','textarea','xmp','noembed','noframes','plaintext','form','object','embed'],
    transformTags: {
      a: (_tag, attrs) => ({ tagName: 'a', attribs: { ...attrs, href: '#', 'data-original-href': attrs.href ?? '', rel: 'noopener noreferrer' } }),
      img: (_tag, attrs) => ({ tagName: 'img', attribs: { ...attrs, src: safeEmbeddedImage(attrs.src??'')??rewrite(attrs.src ?? '')??'', srcset: '' } }),
      iframe:(_tag,attrs)=>{const src=safeYoutubeEmbed(attrs.src??'');return src?{tagName:'iframe',attribs:{src,title:attrs.title??'YouTube video player',width:attrs.width??'560',height:attrs.height??'315',allow:'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share',allowfullscreen:'',loading:'lazy',referrerpolicy:'strict-origin-when-cross-origin'}}:{tagName:'span',attribs:{}}},
      source: (_tag, attrs) => ({ tagName: 'source', attribs: { ...attrs, src: rewrite(attrs.src ?? '') ?? '', srcset: '' } }),
      link: (_tag,attrs)=>({tagName:'link',attribs:{rel:attrs.rel?.toLowerCase()==='stylesheet'?'stylesheet':'',href:attrs.rel?.toLowerCase()==='stylesheet'?(rewrite(attrs.href??'')??''):'',...(attrs.media?{media:attrs.media}:{})}}),
    },
    exclusiveFilter: frame => ['form','object','embed'].includes(frame.tag),
  });
  const styles = $source('style').map((_i, el) => safeCss($source(el).html() ?? '', rewrite)).get().join('\n');
  const $ = cheerio.load(cleaned); $('*').each((_i, el) => {
    const node = $(el); for (const name of Object.keys(node.attr() ?? {})) if (/^on/i.test(name)) node.removeAttr(name);
    const inline = node.attr('style'); if (inline) node.attr('style', safeCss(inline, rewrite));
  });
  let offset = 0; const blocks: SanitizedDocument['blocks'] = [];const occurrences=new Map<string,number>();
  $(blockSelector).each((ordinal, el) => {
    const node = $(el); if (node.parents(blockSelector).length && !['img','svg','video'].includes(el.tagName)) return;
    const type = el.tagName === 'img' ? 'image' : el.tagName === 'svg' ? 'svg' : el.tagName === 'table' ? 'table' : el.tagName === 'figure' ? 'diagram' : el.tagName === 'video' ? 'video' : 'text';
    const text = node.text().replace(/\s+/g, ' ').trim() || node.attr('alt') || node.attr('aria-label') || '';
    const signature=`${el.tagName}\0${text}`,occurrence=occurrences.get(signature)??0;occurrences.set(signature,occurrence+1);const stable = createHash('sha256').update(`${signature}\0${occurrence}`).digest('hex').slice(0, 20);
    const id = `block-${stable}`; node.attr('data-block-id', id); node.attr('tabindex', type === 'text' ? '-1' : '0');
    const visual=type==='image'?node.attr('src'):type==='svg'?$.html(el):undefined;
    blocks.push({ id, ordinal: blocks.length, type, text, ...(visual?{visual}:{}), start: offset, end: offset + text.length }); offset += text.length + 2;
  });
  const canonicalText = blocks.map(block => block.text).filter(Boolean).join('\n\n');
  const title = sourceTitle || $('h1').first().text().trim() || entryPath.split('/').pop()?.replace(/\.html?$/i, '') || 'Untitled';
  cleaned = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">${$('head link[rel="stylesheet"][href]').toString()}<style>${styles}\n${READER_CSS}</style></head><body>${$('body').html() ?? $.root().html()}<script nonce="__AFTERDRAFT_NONCE__">${BRIDGE}</script></body></html>`;
  return { html: cleaned, title, canonicalText, blocks };
}

export const READER_CSS = `:root{color-scheme:light dark}html{overflow-x:hidden}body{box-sizing:border-box;width:min(calc(100% - clamp(2rem,6vw,6rem)),1200px);max-width:none;margin:clamp(1.5rem,4vw,3rem) auto;padding:0;font:18px/1.65 ui-serif,Georgia,serif}body *{box-sizing:border-box}img,svg,table,video{max-width:100%;height:auto}pre,table{overflow:auto}[data-block-id]{scroll-margin:20vh}.afterdraft-highlight{background:#ffe58a}.afterdraft-discussion{background:#dbe8dc;text-decoration:underline dotted #526b58;cursor:pointer}.afterdraft-definition{background:#e5ddf3;text-decoration:underline dotted #6b5684;cursor:pointer}details[data-afterdraft-section]>summary{cursor:pointer;list-style-position:outside}details[data-afterdraft-section]>summary>h1,details[data-afterdraft-section]>summary>h2,details[data-afterdraft-section]>summary>h3,details[data-afterdraft-section]>summary>h4,details[data-afterdraft-section]>summary>h5,details[data-afterdraft-section]>summary>h6{display:inline}.afterdraft-edit-mode [data-block-id]{outline:1px dashed transparent;outline-offset:3px}.afterdraft-edit-mode [data-block-id]:hover{outline-color:#8a6248;background:#fff4cf33}.afterdraft-edit-mode img[data-block-id]{cursor:nwse-resize}.afterdraft-inline-edit{outline:2px solid #8a6248!important;background:#fff9e8!important}.afterdraft-image-resize-selected{outline:2px solid #8a6248!important;outline-offset:3px}.afterdraft-image-resize-box{position:absolute;z-index:2147483646;border:1px solid #8a6248;pointer-events:none}.afterdraft-image-resize-handle{position:absolute;right:-9px;bottom:-9px;width:18px;height:18px;border:2px solid #fff;border-radius:50%;background:#8a6248;box-shadow:0 1px 5px #0006;cursor:nwse-resize;touch-action:none;pointer-events:auto}`;
export const BRIDGE = `(()=>{
const send=(type,data={})=>parent.postMessage({source:'afterdraft',type,...data},'*');let editMode=false,editing=null,selectedImage=null,resizeBox=null,resizing=null;
const byId=id=>document.querySelector('[data-block-id="'+CSS.escape(id)+'"]');
const layout=()=>send('layout',{ratio:scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight),blocks:[...document.querySelectorAll('[data-block-id]')].map(el=>({blockId:el.dataset.blockId,top:el.getBoundingClientRect().top,height:el.getBoundingClientRect().height}))});
const mark=a=>{const el=byId(a.blockId);if(!el||!a.exact||el.querySelector('[data-anchor-id="'+CSS.escape(a.id)+'"]'))return;const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){const index=node.data.indexOf(a.exact);if(index>=0){const range=document.createRange();range.setStart(node,index);range.setEnd(node,index+a.exact.length);const span=document.createElement('mark');span.dataset.anchorId=a.id;span.className=a.checked?'afterdraft-highlight':a.action==='define'?'afterdraft-definition':'afterdraft-discussion';span.tabIndex=0;span.setAttribute('aria-label',(a.checked?'Checked highlight: ':a.action==='define'?'Definition: ':'Discussion: ')+a.exact);range.surroundContents(span);break}}};
const clearMarks=()=>document.querySelectorAll('[data-anchor-id]').forEach(mark=>mark.replaceWith(...mark.childNodes));
const capture=el=>{if(!['TABLE','FIGURE'].includes(el.tagName))return;const rect=el.getBoundingClientRect(),width=Math.min(1800,Math.max(1,Math.ceil(rect.width))),height=Math.min(1800,Math.max(1,Math.ceil(rect.height))),markup=new XMLSerializer().serializeToString(el),svg='<svg xmlns="http://www.w3.org/2000/svg" width="'+width+'" height="'+height+'"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">'+markup+'</div></foreignObject></svg>',image=new Image();image.onload=()=>{try{const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,width,height);context.drawImage(image,0,0);send('visual-capture',{blockId:el.dataset.blockId,mimeType:'image/png',data:canvas.toDataURL('image/png').split(',')[1]})}catch{}};image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)};
const offsets=(el,range)=>{const before=range.cloneRange();before.selectNodeContents(el);before.setEnd(range.startContainer,range.startOffset);return{start:before.toString().length,end:before.toString().length+range.toString().length}};
const rangeFor=(el,start,end)=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node,offset=0,startNode=null,endNode=null,startLocal=0,endLocal=0;while(node=walker.nextNode()){const next=offset+node.data.length;if(startNode===null&&start>=offset&&start<=next){startNode=node;startLocal=start-offset}if(endNode===null&&end>=offset&&end<=next){endNode=node;endLocal=end-offset;break}offset=next}if(!startNode||!endNode)return null;const range=document.createRange();range.setStart(startNode,startLocal);range.setEnd(endNode,endLocal);return range};
const selected=()=>{if(editMode)return;const s=getSelection();if(!s||s.isCollapsed)return;const r=s.getRangeAt(0),origin=r.commonAncestorContainer.nodeType===1?r.commonAncestorContainer:r.commonAncestorContainer.parentElement;if(origin?.closest('[data-anchor-id]'))return;const el=origin?.closest('[data-block-id]');if(!el)return;const exact=s.toString(),full=el.textContent||'',local=Math.max(0,full.indexOf(exact));send('selection',{blockId:el.dataset.blockId,exact,prefix:full.slice(Math.max(0,local-32),local),suffix:full.slice(local+exact.length,local+exact.length+32),startOffset:local,endOffset:local+exact.length,rect:r.getBoundingClientRect().toJSON()})};
const visualTarget=origin=>{const semantic=origin.closest('figure[data-block-id],table[data-block-id],video[data-block-id]');if(semantic)return semantic;return origin.closest('img[data-block-id],svg[data-block-id]')};
const captionFor=el=>{const host=el.tagName==='TABLE'?el:(el.tagName==='FIGURE'?el:el.closest('figure'));const caption=host?.querySelector(':scope > caption,:scope > figcaption');return{label:caption?.querySelector('[data-afterdraft-caption-label]')?.textContent||'',number:caption?.querySelector('[data-afterdraft-caption-number]')?.textContent||'',caption:caption?.querySelector('[data-afterdraft-caption-text]')?.textContent||caption?.textContent?.trim()||''}};
const positionResizeBox=()=>{if(!selectedImage||!resizeBox)return;const rect=selectedImage.getBoundingClientRect();resizeBox.style.left=rect.left+scrollX+'px';resizeBox.style.top=rect.top+scrollY+'px';resizeBox.style.width=rect.width+'px';resizeBox.style.height=rect.height+'px'};
const clearImageResize=()=>{selectedImage?.classList.remove('afterdraft-image-resize-selected');resizeBox?.remove();selectedImage=null;resizeBox=null;resizing=null};
const finishResize=e=>{if(!resizing||e.pointerId!==resizing.pointerId)return;const changed=resizing.width!==resizing.startWidth,blockId=selectedImage?.dataset.blockId,width=resizing.width;resizing=null;if(changed&&blockId)send('edit-operation',{operation:{type:'resize-image',blockId,width}})};
const selectImage=el=>{if(selectedImage===el){positionResizeBox();return}clearImageResize();selectedImage=el;el.classList.add('afterdraft-image-resize-selected');resizeBox=document.createElement('div');resizeBox.className='afterdraft-image-resize-box';const handle=document.createElement('span');handle.className='afterdraft-image-resize-handle';handle.setAttribute('role','slider');handle.setAttribute('aria-label','Resize image');handle.setAttribute('aria-valuemin','48');handle.setAttribute('aria-valuemax','4000');handle.setAttribute('aria-valuenow',String(Math.round(el.getBoundingClientRect().width)));resizeBox.append(handle);document.body.append(resizeBox);positionResizeBox();handle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation()});handle.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();handle.setPointerCapture(e.pointerId);const width=Math.round(el.getBoundingClientRect().width);resizing={pointerId:e.pointerId,startX:e.clientX,startWidth:width,width}});handle.addEventListener('pointermove',e=>{if(!resizing||e.pointerId!==resizing.pointerId)return;const maximum=Math.min(4000,Math.max(48,el.parentElement?.clientWidth||4000)),width=Math.round(Math.min(maximum,Math.max(48,resizing.startWidth+e.clientX-resizing.startX)));resizing.width=width;el.setAttribute('width',String(width));el.removeAttribute('height');el.style.setProperty('width',width+'px','important');el.style.setProperty('height','auto','important');handle.setAttribute('aria-valuenow',String(width));positionResizeBox()});handle.addEventListener('pointerup',finishResize);handle.addEventListener('pointercancel',finishResize)};
const editContext=e=>{if(!editMode)return;e.preventDefault();finishEditing();const origin=e.target.nodeType===1?e.target:e.target.parentElement,visual=visualTarget(origin),text=origin.closest('h1[data-block-id],h2[data-block-id],h3[data-block-id],h4[data-block-id],h5[data-block-id],h6[data-block-id],p[data-block-id],li[data-block-id],blockquote[data-block-id],pre[data-block-id],figcaption[data-block-id],caption[data-block-id]'),el=visual||text;if(!el)return;let start=0,end=(el.textContent||'').length,selectedText='',formats={bold:false,italic:false,underline:false};const selection=getSelection();if(text&&selection&&!selection.isCollapsed&&text.contains(selection.anchorNode)&&text.contains(selection.focusNode)){const value=offsets(text,selection.getRangeAt(0));start=value.start;end=value.end;selectedText=selection.toString();const parent=selection.anchorNode.nodeType===1?selection.anchorNode:selection.anchorNode.parentElement;formats={bold:Boolean(parent?.closest('strong[data-afterdraft-format="bold"]')),italic:Boolean(parent?.closest('em[data-afterdraft-format="italic"]')),underline:Boolean(parent?.closest('u[data-afterdraft-format="underline"]'))}}const details=text?.closest('summary')?.parentElement?.matches('details[data-afterdraft-section]')?text.closest('summary').parentElement:null;send('edit-context',{blockId:el.dataset.blockId,kind:visual?'visual':/^H[1-6]$/.test(el.tagName)?'heading':'text',tag:el.tagName.toLowerCase(),text:el.textContent||'',startOffset:start,endOffset:end,selectedText,formats,folded:details?!details.open:null,caption:visual?captionFor(visual):null,rect:{top:e.clientY,left:e.clientX,width:0,height:0}})};
const finishEditing=()=>{if(!editing)return;const{el,originalText}=editing;el.contentEditable='false';el.classList.remove('afterdraft-inline-edit');const text=el.textContent||'';editing=null;if(text!==originalText)send('edit-operation',{operation:{type:'replace-text',blockId:el.dataset.blockId,text}})};
const startEditing=id=>{finishEditing();const el=byId(id);if(!el)return;editing={el,originalText:el.textContent||'',originalHtml:el.innerHTML};el.contentEditable='true';el.classList.add('afterdraft-inline-edit');el.focus();const selection=getSelection();if(!selection||!el.contains(selection.anchorNode)){const range=document.createRange();range.selectNodeContents(el);range.collapse(false);selection?.removeAllRanges();selection?.addRange(range)}};
const applyFormat=operation=>{const el=byId(operation.blockId),range=el&&rangeFor(el,operation.startOffset,operation.endOffset);if(!el||!range)return;if(operation.enabled){const wrapper=document.createElement(operation.style==='bold'?'strong':operation.style==='italic'?'em':'u');wrapper.dataset.afterdraftFormat=operation.style;try{wrapper.append(range.extractContents());range.insertNode(wrapper)}catch{}}else el.querySelectorAll('[data-afterdraft-format="'+operation.style+'"]').forEach(wrapper=>{if(range.intersectsNode(wrapper))wrapper.replaceWith(...wrapper.childNodes)})};
const applyFold=operation=>{const heading=byId(operation.blockId);if(!heading)return;let details=heading.closest('summary')?.parentElement;if(details?.matches('details[data-afterdraft-section]')){details.open=!operation.folded;return}const level=Number(heading.tagName[1]),detailsNode=document.createElement('details'),summary=document.createElement('summary');detailsNode.dataset.afterdraftSection='';summary.dataset.afterdraftSectionTitle='';detailsNode.open=!operation.folded;heading.before(detailsNode);detailsNode.append(summary);summary.append(heading);let next=detailsNode.nextSibling;while(next){const following=next.nextSibling;if(next.nodeType===1&&(next.tagName==='SCRIPT'||(/^H[1-6]$/.test(next.tagName)&&Number(next.tagName[1])<=level)))break;detailsNode.append(next);next=following}};
const applyCaption=operation=>{const target=byId(operation.blockId);if(!target)return;let caption;if(target.tagName==='TABLE'){caption=target.querySelector(':scope > caption');if(!caption){caption=document.createElement('caption');target.prepend(caption)}}else{let figure=target.tagName==='FIGURE'?target:target.closest('figure');if(!figure){figure=document.createElement('figure');figure.dataset.afterdraftCaptionHost='';target.before(figure);figure.append(target)}caption=figure.querySelector(':scope > figcaption');if(!caption){caption=document.createElement('figcaption');figure.append(caption)}}if(!operation.label&&!operation.number&&!operation.caption){if(caption.dataset.afterdraftCaption!==undefined)caption.remove();return}caption.dataset.afterdraftCaption='';caption.textContent='';const add=(attribute,value)=>{if(!value)return;const span=document.createElement('span');span.dataset[attribute]='';span.textContent=value;caption.append(span)};add('afterdraftCaptionLabel',operation.label);if(operation.label&&operation.number)caption.append(' ');add('afterdraftCaptionNumber',operation.number);if(operation.label||operation.number)caption.append(operation.caption?'. ':'.');add('afterdraftCaptionText',operation.caption)};
let frame;document.addEventListener('scroll',()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{layout();positionResizeBox()})},{passive:true});addEventListener('resize',()=>{layout();positionResizeBox()});document.addEventListener('mouseup',selected);document.addEventListener('keyup',e=>{if(e.shiftKey)selected()});document.addEventListener('contextmenu',editContext);document.addEventListener('paste',e=>{if(editing&&editing.el.contains(e.target)){e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'))}});document.addEventListener('keydown',e=>{if(editing&&(e.ctrlKey||e.metaKey)&&['b','i','u'].includes(e.key.toLowerCase()))e.preventDefault();if(editing&&e.key==='Escape'){editing.el.innerHTML=editing.originalHtml;editing.el.blur()}if(editing&&(e.ctrlKey||e.metaKey)&&e.key==='Enter')editing.el.blur()});document.addEventListener('focusout',e=>{const leaving=e.target;if(editing&&leaving===editing.el)setTimeout(()=>{if(editing?.el===leaving)finishEditing()})});
document.addEventListener('click',e=>{const origin=e.target.nodeType===1?e.target:e.target.parentElement;if(editMode){send('background-click');const image=origin.closest('img[data-block-id]'),text=origin.closest('h1[data-block-id],h2[data-block-id],h3[data-block-id],h4[data-block-id],h5[data-block-id],h6[data-block-id],p[data-block-id],li[data-block-id],blockquote[data-block-id],pre[data-block-id],figcaption[data-block-id],caption[data-block-id]');if(image){e.preventDefault();finishEditing();selectImage(image);return}clearImageResize();if(text){if(!editing||editing.el!==text){e.preventDefault();startEditing(text.dataset.blockId)}return}finishEditing();return}const el=origin.closest('[data-block-id]'),visual=el&&['IMG','SVG','TABLE','FIGURE','VIDEO'].includes(el.tagName),anchor=origin.closest('[data-anchor-id]');if(visual){send('block-selection',{blockId:el.dataset.blockId,blockType:el.tagName.toLowerCase(),rect:el.getBoundingClientRect().toJSON()});capture(el)}if(anchor)send('anchor-click',{anchorId:anchor.dataset.anchorId});if(!visual&&!anchor&&(getSelection()?.isCollapsed??true))send('background-click')});
addEventListener('message',e=>{const data=e.data||{};if(data.type==='scroll-to-block'){const target=byId(data.blockId);target?.scrollIntoView({behavior:'smooth',block:'center'});target?.focus({preventScroll:true})}if(data.type==='restore-progress')scrollTo(0,Math.max(0,data.ratio)*Math.max(0,document.documentElement.scrollHeight-innerHeight));if(data.type==='apply-anchors'&&!editMode)data.anchors.forEach(mark);if(data.type==='enter-edit-mode'){editMode=true;clearMarks();document.documentElement.classList.add('afterdraft-edit-mode')}if(data.type==='start-inline-edit')startEditing(data.blockId);if(data.type==='apply-edit-operation'){finishEditing();if(data.operation.type==='format-text')applyFormat(data.operation);if(data.operation.type==='fold-section')applyFold(data.operation);if(data.operation.type==='set-caption')applyCaption(data.operation)}if(data.type==='finish-editing'){finishEditing();send('edit-finished',{requestId:data.requestId})}if(data.type==='exit-edit-mode'){finishEditing();clearImageResize();editMode=false;document.documentElement.classList.remove('afterdraft-edit-mode')}});
send('ready',{});setTimeout(layout,50)})();`;
