import { describe,expect,it } from 'vitest';
import { BRIDGE,normalizeAssetPath,sanitizeDocument,sanitizeStylesheet } from './sanitize.js';
describe('sanitization',()=>{
  it('rejects traversal and external resources',()=>{expect(normalizeAssetPath('', '../secret')).toBeNull();expect(normalizeAssetPath('article','https://evil.test/x')).toBeNull();expect(normalizeAssetPath('article','../img/a.png')).toBe('img/a.png');});
  it('removes active content and assigns blocks',()=>{const result=sanitizeDocument('<html><head><style>@import "https://evil";p{background:url(https://evil)}</style></head><body><script>alert(1)</script><form>x</form><p onclick="x()">Hello world</p><img src="img.png" onerror="x()"></body></html>','index.html',p=>`/asset/${p}`);expect(result.html).not.toContain('onclick');expect(result.html).not.toContain('alert(1)');expect(result.html).not.toContain('https://evil');expect(result.html).toContain('data-block-id');expect(result.canonicalText).toContain('Hello world');});
  it('preserves local stylesheets and rewrites nested CSS assets',()=>{const result=sanitizeDocument('<html><head><link rel="stylesheet" href="css/main.css"></head><body><p>Hello</p></body></html>','index.html',p=>`/asset/${p}`);expect(result.html).toContain('href="/asset/css/main.css"');const css=sanitizeStylesheet('@import "https://evil";.hero{background:url(../img/a.png)}','css/main.css',p=>`/asset/${p}`);expect(css).not.toContain('@import');expect(css).toContain('/asset/img/a.png')});
  it('preserves a safe video container as a caption target without remote playback',()=>{const result=sanitizeDocument('<video controls aria-label="Demonstration"><source src="https://evil.test/demo.mp4"></video>','index.html',p=>`/asset/${p}`);expect(result.html).toContain('<video controls="" aria-label="Demonstration"');expect(result.html).not.toContain('evil.test');expect(result.blocks).toEqual(expect.arrayContaining([expect.objectContaining({type:'video',text:'Demonstration'})]))});
  it('keeps validated embedded raster images and only YouTube embeds',()=>{const png='data:image/png;base64,iVBORw0KGgo=',result=sanitizeDocument(`<img src="${png}"><img src="data:image/svg+xml;base64,PHN2Zz48L3N2Zz4="><iframe src="https://www.youtube.com/embed/1kXnsvYfaF4?start=1302"></iframe><iframe src="https://evil.test/embed/1kXnsvYfaF4"></iframe>`,'index.html',()=>null);expect(result.html).toContain(png);expect(result.html).not.toContain('src="data:image/svg+xml');expect(result.html).toContain('https://www.youtube-nocookie.com/embed/1kXnsvYfaF4?start=1302');expect(result.html).not.toContain('evil.test')});
  it('ships a syntactically valid sandbox bridge with edit-mode messages',()=>{expect(()=>new Function(BRIDGE)).not.toThrow();expect(BRIDGE).toContain('edit-context');expect(BRIDGE).toContain('finish-editing')});
});
