import {useCallback,useEffect,useState} from 'react';
import {AcademicImportDialog,ImportJobTray} from './AcademicImport.js';
import {api} from './api.js';
import {SettingsPage} from './Settings.js';
import type {DocumentRepresentation} from '@profread/shared';

type Document={id:string;title:string;version_id:string;version:number;token_estimate:number;checked_count:number;offset_ratio:number|null;created_at:string;group_id:string|null;representations?:DocumentRepresentation[]};
export function libraryReadingFormats(document:Pick<Document,'representations'>):string{return document.representations?.length?[...new Set(document.representations.map(item=>item.kind.toUpperCase()))].join(' + '):'HTML'}
type ArticleGroup={id:string;name:string;document_count:number;created_at:string;updated_at:string};

export function Library({onOpen,onReviewImport,onLogout}:{onOpen:(id:string)=>void;onReviewImport:(id:string)=>void;onLogout:()=>void}){
  const[documents,setDocuments]=useState<Document[]>([]),[groups,setGroups]=useState<ArticleGroup[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[panel,setPanel]=useState<string|null>(null),[deleteTarget,setDeleteTarget]=useState<Document|null>(null),[importOpen,setImportOpen]=useState(false),[importRefresh,setImportRefresh]=useState(0);
  const load=useCallback(async()=>{try{const[docs,nextGroups]=await Promise.all([api<Document[]>('/api/documents'),api<ArticleGroup[]>('/api/groups')]);setDocuments(docs);setGroups(nextGroups);setError('')}catch(reason){setError((reason as Error).message)}},[]);
  useEffect(()=>{void load()},[load]);
  async function moveDocument(documentId:string,groupId:string|null){try{await api(`/api/documents/${documentId}/group`,{method:'PUT',body:JSON.stringify({groupId})});await load()}catch(reason){setError((reason as Error).message)}}
  async function deleteDocument(){if(!deleteTarget)return;setBusy(true);try{await api(`/api/documents/${deleteTarget.id}`,{method:'DELETE',body:JSON.stringify({confirmTitle:deleteTarget.title})});setDeleteTarget(null);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  const sections=[...groups.map(group=>({id:group.id,name:group.name,documents:documents.filter(document=>document.group_id===group.id)})),{id:null,name:'Ungrouped',documents:documents.filter(document=>!document.group_id)}].filter(section=>section.id!==null||section.documents.length>0||documents.length===0);
  if(panel==='settings')return <SettingsPage onClose={()=>setPanel(null)} onLogout={onLogout}/>;
  return <main className="library">
    <header><div className="library-brand"><span className="eyebrow">Private library</span><img className="profread-logo library-logo" src="/profread_logo.svg" width="1400" height="380" alt="ProfRead — Ask. Critique. Understand."/><h1 className="sr-only">ProfRead</h1></div><div className="header-actions"><button className="quiet" onClick={()=>setPanel(panel==='search'?null:'search')}>Search</button><button className="quiet" onClick={()=>setPanel(panel==='groups'?null:'groups')}>Groups</button><button className="quiet" onClick={()=>setPanel(panel==='repairs'?null:'repairs')}>Repairs</button><button className="quiet" onClick={()=>setPanel('settings')}>AI settings</button><button className="primary" onClick={()=>setImportOpen(true)}>Import article</button><button className="quiet" onClick={onLogout}>Sign out</button></div></header>
    {error&&<p role="alert" className="error">{error}</p>}
    {panel==='search'&&<SearchPanel onOpen={onOpen}/>} {panel==='groups'&&<GroupsPanel groups={groups} onChanged={load}/>} {panel==='repairs'&&<RepairPanel onOpen={onOpen}/>}
    <ImportJobTray refreshToken={importRefresh} onReview={onReviewImport} onOpenDocument={onOpen}/>
    <div aria-label="Article library">{sections.map(section=><section className="article-group-section" key={section.id??'ungrouped'}><header><h2>{section.name}</h2><span>{section.documents.length} article{section.documents.length===1?'':'s'}</span></header><div className="shelf">{section.documents.length===0?(section.id===null?<div className="empty"><span>§</span><h2>Your margin is waiting</h2><p>Import PDF or HTML papers, publisher pages, arXiv material, DOCX drafts, or LaTeX projects.</p></div>:<p className="group-empty">Move an article here using its Group menu.</p>):section.documents.map(doc=><article className="book" key={doc.id}><button className="book-open" onClick={()=>onOpen(doc.id)}><span className="book-rule"/><span className="book-title">{doc.title}</span><span className="book-meta">{libraryReadingFormats(doc)} · Version {doc.version} · {Math.ceil(doc.token_estimate/100)/10}k tokens</span><span className="book-progress"><i style={{width:`${Math.round((doc.offset_ratio??0)*100)}%`}}/></span><span className="book-note">{doc.checked_count} checked highlight{doc.checked_count===1?'':'s'}</span></button><footer className="book-actions"><label><span className="sr-only">Group for {doc.title}</span><select value={doc.group_id??''} onChange={event=>void moveDocument(doc.id,event.target.value||null)}><option value="">Ungrouped</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></label><button className="danger-link" onClick={()=>setDeleteTarget(doc)}>Delete</button></footer></article>)}</div></section>)}</div>
    {importOpen&&<AcademicImportDialog onClose={()=>setImportOpen(false)} onCreated={()=>{setImportOpen(false);setImportRefresh(value=>value+1)}}/>}
    {deleteTarget&&<div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setDeleteTarget(null)}><section className="edit-dialog delete-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-article-title"><header><div><span className="eyebrow">Permanent action</span><h2 id="delete-article-title">Delete article?</h2></div><button className="quiet" onClick={()=>setDeleteTarget(null)}>Close</button></header><p className="delete-title">“{deleteTarget.title}”</p><p>This removes every imported version, edit, annotation, discussion, artifact, search entry, and generated image for this article. Server backups remain available for recovery.</p><footer><button className="quiet" onClick={()=>setDeleteTarget(null)}>Cancel</button><button className="danger" disabled={busy} onClick={()=>void deleteDocument()}>{busy?'Deleting…':'Delete article'}</button></footer></section></div>}
  </main>;
}

function GroupsPanel({groups,onChanged}:{groups:ArticleGroup[];onChanged:()=>Promise<void>}){const[name,setName]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);async function create(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api('/api/groups',{method:'POST',body:JSON.stringify({name})});setName('');setStatus('Group created.');await onChanged()}catch(reason){setStatus((reason as Error).message)}finally{setBusy(false)}}async function rename(id:string,nextName:string){setBusy(true);try{await api(`/api/groups/${id}`,{method:'PATCH',body:JSON.stringify({name:nextName})});setStatus('Group renamed.');await onChanged()}catch(reason){setStatus((reason as Error).message)}finally{setBusy(false)}}async function remove(group:ArticleGroup){if(!confirm(`Delete the group “${group.name}”? Its ${group.document_count} article${group.document_count===1?'':'s'} will become ungrouped.`))return;setBusy(true);try{await api(`/api/groups/${group.id}`,{method:'DELETE'});setStatus('Group deleted; its articles are now ungrouped.');await onChanged()}catch(reason){setStatus((reason as Error).message)}finally{setBusy(false)}}return <section className="library-panel group-manager"><header><div><h2>Article groups</h2><p>Each article can belong to one group. Deleting a group never deletes its articles.</p></div></header><form onSubmit={create}><label>New group<input required maxLength={80} value={name} onChange={event=>setName(event.target.value)} placeholder="For example: Robotics"/></label><button className="primary" disabled={busy}>Create group</button></form><div className="group-list">{groups.length===0?<p>No groups yet.</p>:groups.map(group=><form key={group.id} onSubmit={event=>{event.preventDefault();void rename(group.id,String(new FormData(event.currentTarget).get('name')??''))}}><input name="name" required maxLength={80} defaultValue={group.name} aria-label={`Name for ${group.name}`}/><span>{group.document_count} article{group.document_count===1?'':'s'}</span><button className="quiet" disabled={busy}>Rename</button><button type="button" className="danger-link" disabled={busy} onClick={()=>void remove(group)}>Delete group</button></form>)}</div><p role="status">{status}</p></section>}

function SearchPanel({onOpen}:{onOpen:(id:string)=>void}){const[q,setQ]=useState(''),[type,setType]=useState(''),[results,setResults]=useState<any[]>([]),[error,setError]=useState('');async function search(event:React.FormEvent){event.preventDefault();try{setResults(await api(`/api/search?q=${encodeURIComponent(q)}${type?`&type=${type}`:''}`));setError('')}catch(reason){setError((reason as Error).message)}}return <section className="library-panel"><form onSubmit={search}><label>Search articles and knowledge<input autoFocus value={q} onChange={event=>setQ(event.target.value)} placeholder="A phrase or FTS query"/></label><select aria-label="Result type" value={type} onChange={event=>setType(event.target.value)}><option value="">All types</option><option value="article">Articles</option><option value="answer">Answers</option><option value="artifact">Artifacts</option></select><button className="primary">Search</button></form>{error&&<p className="error">{error}</p>}<div aria-live="polite">{results.map(result=><button className="search-result" key={`${result.kind}-${result.entity_id}`} onClick={()=>onOpen(result.document_id)}><b>{result.title||result.kind}</b><span>{String(result.snippet).replace(/<\/?mark>/g,'')}</span></button>)}</div></section>}

function RepairPanel({onOpen}:{onOpen:(id:string)=>void}){const[items,setItems]=useState<any[]|null>(null);useEffect(()=>{api<any[]>('/api/anchors/repair').then(setItems)},[]);return <section className="library-panel"><h2>Anchor repairs</h2>{items===null?<p>Checking document versions…</p>:items.length===0?<p>Every annotation is attached.</p>:items.map(item=><button className="search-result" key={item.id} onClick={()=>{sessionStorage.setItem('profread-repair-id',item.id);onOpen(item.document_id)}}><b>{item.title}</b><span>Unmatched: “{item.exact_quote}” — open the article and select its new location.</span></button>)}</section>}
