import {useCallback,useEffect,useState} from 'react';
import {api} from './api.js';

export type ReviewerPolicyAction='require-stronger-evidence'|'lower-priority'|'increase-scrutiny'|'context-note';
export type ReviewerPolicy={id:string;name:string;enabled:boolean;priority:number;match:{issueCode?:string;evidenceKind?:string;source?:'deterministic'|'model';sourceAction?:string;sourceKind?:string;domain?:string};action:ReviewerPolicyAction;createdAt:string|null;updatedAt:string|null};
export type ReviewerPolicyDraft={name:string;enabled:boolean;priority:number;issueCode:string;evidenceKind:string;source:''|'deterministic'|'model';sourceAction:string;sourceKind:string;domain:string;action:ReviewerPolicyAction};
const actions:ReviewerPolicyAction[]=['require-stronger-evidence','lower-priority','increase-scrutiny','context-note'];
const empty:ReviewerPolicyDraft={name:'',enabled:true,priority:100,issueCode:'',evidenceKind:'',source:'',sourceAction:'',sourceKind:'',domain:'',action:'require-stronger-evidence'};
const labels:Record<ReviewerPolicyAction,string>={'require-stronger-evidence':'Require stronger evidence','lower-priority':'Lower review priority','increase-scrutiny':'Increase scrutiny','context-note':'Context note'};
function record(value:unknown):Record<string,any>{return value&&typeof value==='object'?value as Record<string,any>: {}}
function text(value:unknown):string{return typeof value==='string'?value.trim():''}
export function normalizeReviewerPolicy(value:unknown,index=0):ReviewerPolicy{const raw=record(value),match=record(raw.match??raw.matcher),source=text(match.source),action=actions.includes(raw.action)?raw.action as ReviewerPolicyAction:'require-stronger-evidence';return{id:String(raw.id??raw.policyId??raw.policy_id??`reviewer-policy-${index+1}`),name:text(raw.name)||'Reviewer guidance',enabled:raw.enabled===undefined?true:Boolean(raw.enabled),priority:Math.max(0,Math.min(10_000,Number.isFinite(Number(raw.priority))?Math.round(Number(raw.priority)):100)),match:{...(text(match.issueCode??match.issue_code)?{issueCode:text(match.issueCode??match.issue_code)}:{}),...(text(match.evidenceKind??match.evidence_kind)?{evidenceKind:text(match.evidenceKind??match.evidence_kind)}:{}),...(['deterministic','model'].includes(source)?{source:source as 'deterministic'|'model'}:{}),...(text(match.sourceAction??match.source_action)?{sourceAction:text(match.sourceAction??match.source_action)}:{}),...(text(match.sourceKind??match.source_kind)?{sourceKind:text(match.sourceKind??match.source_kind)}:{}),...(text(match.domain??match.hostname)?{domain:text(match.domain??match.hostname).toLowerCase()}:{})},action,createdAt:text(raw.createdAt??raw.created_at)||null,updatedAt:text(raw.updatedAt??raw.updated_at)||null}}
export function normalizeReviewerPolicies(value:unknown):ReviewerPolicy[]{const raw=record(value),items=Array.isArray(value)?value:Array.isArray(raw.policies)?raw.policies:[];return items.map(normalizeReviewerPolicy).filter(policy=>Boolean(policy.id))}
function fromPolicy(policy:ReviewerPolicy):ReviewerPolicyDraft{return{name:policy.name,enabled:policy.enabled,priority:policy.priority,issueCode:policy.match.issueCode??'',evidenceKind:policy.match.evidenceKind??'',source:policy.match.source??'',sourceAction:policy.match.sourceAction??'',sourceKind:policy.match.sourceKind??'',domain:policy.match.domain??'',action:policy.action}}
export function reviewerPolicyPayload(value:ReviewerPolicyDraft){return{name:value.name.trim(),enabled:value.enabled,priority:Math.max(0,Math.min(10_000,Math.round(value.priority))),match:{...(value.issueCode.trim()?{issueCode:value.issueCode.trim()}:{}),...(value.evidenceKind.trim()?{evidenceKind:value.evidenceKind.trim()}:{}),...(value.source?{source:value.source}:{}),...(value.sourceAction.trim()?{sourceAction:value.sourceAction.trim()}:{}),...(value.sourceKind.trim()?{sourceKind:value.sourceKind.trim()}:{}),...(value.domain.trim()?{domain:value.domain.trim().toLowerCase()}:{})},action:value.action}}
export function reviewerPolicyScopeLabel(policy:Pick<ReviewerPolicy,'match'>):string{const parts=[policy.match.issueCode&&`issue ${policy.match.issueCode}`,policy.match.evidenceKind&&`evidence ${policy.match.evidenceKind}`,policy.match.source&&`${policy.match.source} findings`,policy.match.sourceAction&&`action ${policy.match.sourceAction}`,policy.match.sourceKind&&`source ${policy.match.sourceKind}`,policy.match.domain&&`domain ${policy.match.domain}`].filter(Boolean);return parts.length?parts.join(' · '):'All review issues'}

export function ReviewerPolicySettings(){
  const[policies,setPolicies]=useState<ReviewerPolicy[]>([]),[draft,setDraft]=useState<ReviewerPolicyDraft>({...empty}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState('');
  const load=useCallback(async()=>{try{setPolicies(normalizeReviewerPolicies(await api('/api/settings/academic-import/reviewer-policies')));setError('')}catch(reason){setError((reason as Error).message)}finally{setLoaded(true)}},[]);
  useEffect(()=>{void load()},[load]);
  async function create(event:React.FormEvent){event.preventDefault();setBusy('create');setStatus('');try{await api('/api/settings/academic-import/reviewer-policies',{method:'POST',body:JSON.stringify(reviewerPolicyPayload(draft))});setDraft({...empty});await load();setStatus('Reviewer guidance created.')}catch(reason){setError((reason as Error).message)}finally{setBusy('')}}
  async function update(id:string,value:ReviewerPolicyDraft){setBusy(id);setStatus('');try{await api(`/api/settings/academic-import/reviewer-policies/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(reviewerPolicyPayload(value))});await load();setStatus('Reviewer guidance updated.')}catch(reason){setError((reason as Error).message)}finally{setBusy('')}}
  async function remove(policy:ReviewerPolicy){if(typeof window!=='undefined'&&!window.confirm(`Delete “${policy.name}”?`))return;setBusy(policy.id);try{await api(`/api/settings/academic-import/reviewer-policies/${encodeURIComponent(policy.id)}`,{method:'DELETE'});await load();setStatus('Reviewer guidance deleted.')}catch(reason){setError((reason as Error).message)}finally{setBusy('')}}
  return <section className="reviewer-policy-settings" aria-labelledby="reviewer-policy-title"><header><div><h2 id="reviewer-policy-title">Reviewer guidance memory</h2><p>Transparent preferences can change review emphasis, but never decide an issue or bypass deterministic repair checks.</p></div><button className="quiet" disabled={Boolean(busy)} onClick={()=>void load()}>Refresh</button></header>{error&&<p role="alert" className="settings-note reviewer-policy-error">Reviewer guidance is unavailable: {error}</p>}{loaded&&!error&&policies.length===0&&<p className="settings-note">No saved reviewer guidance. Use “Remember response” from an import review, or create a rule here.</p>}<div className="reviewer-policy-list">{policies.map(policy=><PolicyEditor key={policy.id} policy={policy} busy={busy===policy.id} onSave={value=>void update(policy.id,value)} onDelete={()=>void remove(policy)}/>)}</div><form className="reviewer-policy-create" onSubmit={create}><header><div><b>Create reviewer guidance</b><small>Leave match fields blank only if you intentionally want workspace-wide guidance.</small></div></header><Fields value={draft} onChange={setDraft}/><footer><button className="primary" disabled={busy==='create'||!draft.name.trim()}>{busy==='create'?'Creating…':'Create guidance'}</button></footer></form><p role="status">{status}</p></section>
}

function PolicyEditor({policy,busy,onSave,onDelete}:{policy:ReviewerPolicy;busy:boolean;onSave:(value:ReviewerPolicyDraft)=>void;onDelete:()=>void}){const[value,setValue]=useState(()=>fromPolicy(policy));useEffect(()=>setValue(fromPolicy(policy)),[policy]);const changed=JSON.stringify(value)!==JSON.stringify(fromPolicy(policy));return <article className={`reviewer-policy ${value.enabled?'enabled':'disabled'}`}><header><div><b>{policy.name}</b><small>{reviewerPolicyScopeLabel(policy)} · priority {policy.priority}</small></div><span>{labels[policy.action]}</span></header><Fields value={value} onChange={setValue}/><footer><label className="reviewer-policy-enabled"><input type="checkbox" checked={value.enabled} onChange={event=>setValue(current=>({...current,enabled:event.target.checked}))}/> Enabled</label><button className="danger-link" disabled={busy} onClick={onDelete}>Delete</button><button className="primary" disabled={busy||!changed||!value.name.trim()} onClick={()=>onSave(value)}>Save changes</button></footer></article>}

function Fields({value,onChange}:{value:ReviewerPolicyDraft;onChange:(value:ReviewerPolicyDraft)=>void}){return <div className="reviewer-policy-fields"><label>Name<input required maxLength={160} value={value.name} onChange={event=>onChange({...value,name:event.target.value})}/></label><label>Guidance<select value={value.action} onChange={event=>onChange({...value,action:event.target.value as ReviewerPolicyAction})}>{actions.map(action=><option value={action} key={action}>{labels[action]}</option>)}</select></label><label>Issue category<input maxLength={64} value={value.issueCode} placeholder="e.g. table-overflow" onChange={event=>onChange({...value,issueCode:event.target.value})}/></label><label>Evidence kind<input maxLength={64} value={value.evidenceKind} placeholder="optional" onChange={event=>onChange({...value,evidenceKind:event.target.value})}/></label><label>Finding source<select value={value.source} onChange={event=>onChange({...value,source:event.target.value as ReviewerPolicyDraft['source']})}><option value="">Any</option><option value="deterministic">Deterministic</option><option value="model">Model reviewer</option></select></label><label>Reviewer action<input maxLength={64} value={value.sourceAction} placeholder="optional" onChange={event=>onChange({...value,sourceAction:event.target.value})}/></label><label>Import source<input maxLength={32} value={value.sourceKind} placeholder="pdf, url, docx…" onChange={event=>onChange({...value,sourceKind:event.target.value})}/></label><label>Publisher domain<input maxLength={253} value={value.domain} placeholder="publisher.example" onChange={event=>onChange({...value,domain:event.target.value})}/></label><label>Priority<input type="number" min={0} max={10000} value={value.priority} onChange={event=>onChange({...value,priority:Number(event.target.value)})}/></label></div>}
