import {useEffect,useMemo,useState} from 'react';
import {api} from './api.js';

type Prompt={key:string;category:string;label:string;description:string;template:string;defaultTemplate:string;variables:string[];overridden:boolean;updatedAt:string|null};
type BehaviorDefinition={key:string;label:string;description:string;min:number;max:number;step:number;unit:string};
type Behavior={values:Record<string,number>;defaults:Record<string,number>;definitions:BehaviorDefinition[];customized:boolean;updatedAt:string|null};
const actions=[['define','Define one word'],['explain','Explain'],['eli14','Explain for a 14-year-old'],['ask','Ask / follow-up'],['polish-note','Polish annotation'],['visualize','Structured diagram'],['research','Web research'],['summarize','Summarize'],['tldr','TL;DR'],['compact','Compact note'],['half-page','Half-page summary'],['visual-recap','Visual recap image']] as const;
const taskLabels=Object.fromEntries(actions);

export function SettingsPage({onClose,onLogout}:{onClose:()=>void;onLogout:()=>void}){
 const[tab,setTab]=useState<'prompts'|'models'|'advanced'>('prompts'),[models,setModels]=useState<any>(null),[prompts,setPrompts]=useState<Prompt[]|null>(null),[behavior,setBehavior]=useState<Behavior|null>(null),[error,setError]=useState('');
 const loadModels=async()=>setModels(await api('/api/settings/models')),loadPrompts=async()=>setPrompts(await api<Prompt[]>('/api/settings/prompts')),loadBehavior=async()=>setBehavior(await api<Behavior>('/api/settings/behavior'));
 useEffect(()=>{Promise.all([loadModels(),loadPrompts(),loadBehavior()]).catch(next=>setError((next as Error).message))},[]);
 return <main className="settings-page"><header className="settings-page-header"><div><span className="eyebrow">AfterDraft workspace</span><h1>Settings</h1><p>Review the instructions and routing that shape each AI action.</p></div><div className="header-actions"><button className="quiet" onClick={onClose}>Back to library</button><button className="quiet" onClick={onLogout}>Sign out</button></div></header><nav className="settings-tabs" aria-label="Settings sections"><button className={tab==='prompts'?'active':''} onClick={()=>setTab('prompts')}>Action prompts</button><button className={tab==='models'?'active':''} onClick={()=>setTab('models')}>Models & routing</button><button className={tab==='advanced'?'active':''} onClick={()=>setTab('advanced')}>Context & advanced</button></nav>{error&&<p role="alert" className="error">{error}</p>}{!models||!prompts||!behavior?<section className="settings-section"><p>Loading settings…</p></section>:<>{tab==='prompts'&&<ActionPrompts prompts={prompts} routes={models.taskRoutes} models={models.models} onChanged={loadPrompts}/>} {tab==='models'&&<ModelSettings data={models} onChanged={loadModels}/>} {tab==='advanced'&&<Advanced prompts={prompts} behavior={behavior} onPromptsChanged={loadPrompts} onBehaviorChanged={loadBehavior}/>}</>}</main>
}

function ActionPrompts({prompts,routes,models,onChanged}:{prompts:Prompt[];routes:any[];models:any[];onChanged:()=>Promise<void>}){const routeMap=useMemo(()=>new Map(routes.map(route=>[route.action,route.modelId])),[routes]);return <section className="settings-section"><h2>Action prompts</h2><p>Edit the human-readable request and output contract for each action. Changes apply to the next request.</p><p className="settings-note">Highlight is not listed because it is a local annotation action and does not call an AI model.</p><div className="action-prompt-list">{actions.map(([action,label])=>{const request=prompts.find(prompt=>prompt.key===`request.${action}`),contract=prompts.find(prompt=>prompt.key===`contract.${action}`),model=models.find(item=>item.id===routeMap.get(action));return <article className="action-prompt-group" key={action}><header><div><span className="eyebrow">{action}</span><h3>{label}</h3></div><small>{model?.label??routeMap.get(action)??'No model route'}</small></header>{request?<PromptEditor prompt={request} onChanged={onChanged}/>:<p className="settings-note">The request is the question you type, so this action has only an output contract.</p>}{contract&&<PromptEditor prompt={contract} onChanged={onChanged}/>}</article>})}</div></section>}

function ModelSettings({data,onChanged}:{data:any;onChanged:()=>Promise<void>}){const[status,setStatus]=useState(''),routes=new Map(data.taskRoutes.map((route:any)=>[route.action,route.modelId]));async function saveTask(action:string,modelId:string){try{await api(`/api/settings/tasks/${action}`,{method:'PUT',body:JSON.stringify({modelId})});setStatus(`${taskLabels[action]??action} now uses ${data.models.find((model:any)=>model.id===modelId)?.label??modelId}.`);await onChanged()}catch(error){setStatus((error as Error).message)}}async function saveProvider(provider:any,form:HTMLFormElement){const values=new FormData(form);try{await api(`/api/settings/providers/${provider.id}`,{method:'PUT',body:JSON.stringify({label:values.get('label'),protocol:provider.protocol,baseUrl:values.get('baseUrl'),secretEnvName:values.get('secretEnvName'),enabled:values.get('enabled')==='on',config:JSON.parse(provider.config_json||'{}')})});setStatus('Saved. Provider keys remain server-side environment variables.');await onChanged()}catch(error){setStatus((error as Error).message)}}return <section className="settings-section model-settings"><h2>Model readiness</h2><p>All three GPT-5.6 tiers stay available during a reading session; the action determines which model runs.</p><div className="model-ready-grid">{data.models.map((model:any)=><article className={`model-ready ${model.ready?'ready':'unavailable'}`} key={model.id}><span>{model.ready?'Ready':'Provider unavailable'}</span><b>{model.label}</b><small>{model.id}</small></article>)}</div><h3>Task routing</h3><p>Choose the default model for each action. The reader toolbar can override one request.</p><div className="task-routing-grid">{actions.map(([action,label])=><label key={action}><span>{label}</span><select value={String(routes.get(action)??'')} onChange={event=>void saveTask(action,event.target.value)}>{data.models.map((model:any)=><option key={model.id} value={model.id}>{model.label}{model.ready?'':' (not ready)'}</option>)}</select></label>)}</div><h3>Providers</h3><p>Configure server-side key references, never secret values.</p>{data.providers.map((provider:any)=><form className="provider-form" key={provider.id} onSubmit={event=>{event.preventDefault();void saveProvider(provider,event.currentTarget)}}><input name="label" defaultValue={provider.label} aria-label="Provider label"/><input name="baseUrl" defaultValue={provider.base_url??''} aria-label="Base URL"/><input name="secretEnvName" defaultValue={provider.secret_env_name} aria-label="Secret environment variable"/><label><input name="enabled" type="checkbox" defaultChecked={Boolean(provider.enabled)}/> Enabled</label><button className="primary">Save</button></form>)}<p role="status">{status}</p></section>}

function Advanced({prompts,behavior,onPromptsChanged,onBehaviorChanged}:{prompts:Prompt[];behavior:Behavior;onPromptsChanged:()=>Promise<void>;onBehaviorChanged:()=>Promise<void>}){const advanced=prompts.filter(prompt=>!['Action requests','Action contracts'].includes(prompt.category)),categories=[...new Set(advanced.map(prompt=>prompt.category))];return <section className="settings-section"><h2>Context assembly</h2><p>Control when AfterDraft sends the whole article, how cached contexts are sized, and how much discussion history is retained.</p><BehaviorEditor settings={behavior} onChanged={onBehaviorChanged}/><h2>Advanced prompt components</h2><p>These templates combine action prompts with article context, repair structured output, and classify free-form questions.</p><div className="prompt-groups">{categories.map(category=><details key={category}><summary><b>{category}</b><span>{advanced.filter(prompt=>prompt.category===category).length} templates</span></summary><div className="prompt-template-list">{advanced.filter(prompt=>prompt.category===category).map(prompt=><PromptEditor key={prompt.key} prompt={prompt} onChanged={onPromptsChanged}/>)}</div></details>)}</div></section>}

function BehaviorEditor({settings,onChanged}:{settings:Behavior;onChanged:()=>Promise<void>}){const[values,setValues]=useState(settings.values),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setValues(settings.values),[settings.values]);async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api('/api/settings/behavior',{method:'PUT',body:JSON.stringify(values)});setStatus('Saved. Cached article contexts will be rebuilt when next needed.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}async function reset(){setBusy(true);try{await api('/api/settings/behavior',{method:'DELETE'});setStatus('Reset to source defaults.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}const changed=settings.definitions.some(item=>values[item.key]!==settings.values[item.key]);return <form className="behavior-settings" onSubmit={save}><header><span className={settings.customized?'overridden':'default'}>{settings.customized?'Customized':'Source defaults'}</span><button type="button" className="quiet" disabled={busy||!settings.customized} onClick={()=>void reset()}>Reset all</button></header><div className="behavior-settings-grid">{settings.definitions.map(item=><label key={item.key}><span>{item.label}</span><small>{item.description}</small><span className="number-field"><input type="number" required min={item.min} max={item.max} step={item.step} value={values[item.key]} onChange={event=>setValues(current=>({...current,[item.key]:Number(event.target.value)}))}/><i>{item.unit}</i></span></label>)}</div><footer><button className="primary" disabled={busy||!changed}>Save context settings</button><span role="status">{status}</span></footer></form>}

function PromptEditor({prompt,onChanged}:{prompt:Prompt;onChanged:()=>Promise<void>}){const[value,setValue]=useState(prompt.template),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setValue(prompt.template),[prompt.template]);async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api(`/api/settings/prompts/${encodeURIComponent(prompt.key)}`,{method:'PUT',body:JSON.stringify({template:value})});setStatus('Saved.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}async function reset(){setBusy(true);try{await api(`/api/settings/prompts/${encodeURIComponent(prompt.key)}`,{method:'DELETE'});setStatus('Reset to source default.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}return <form className="prompt-template" onSubmit={save}><header><div><b>{prompt.label}</b><code>{prompt.key}</code></div><span className={prompt.overridden?'overridden':'default'}>{prompt.overridden?'Customized':'Default'}</span></header><p>{prompt.description}</p>{prompt.variables.length>0&&<small>Variables: {prompt.variables.map(variable=><code key={variable}>{`{{${variable}}}`}</code>)}</small>}<textarea aria-label={`${prompt.label} template`} rows={Math.min(16,Math.max(3,value.split('\n').length+1))} value={value} onChange={event=>setValue(event.target.value)}/><footer><button className="primary" disabled={busy||value===prompt.template}>Save template</button><button type="button" className="quiet" disabled={busy||!prompt.overridden} onClick={()=>void reset()}>Reset to default</button><span role="status">{status}</span></footer></form>}
