import {useEffect,useMemo,useState} from 'react';
import {api} from './api.js';
import {ReviewerPolicySettings} from './ReviewerPolicySettings.js';
export {normalizeReviewerPolicies,reviewerPolicyPayload,reviewerPolicyScopeLabel} from './ReviewerPolicySettings.js';

type Prompt={key:string;category:string;label:string;description:string;template:string;defaultTemplate:string;variables:string[];overridden:boolean;updatedAt:string|null};
type BehaviorDefinition={key:string;label:string;description:string;min:number;max:number;step:number;unit:string};
type Behavior={values:Record<string,number>;defaults:Record<string,number>;definitions:BehaviorDefinition[];customized:boolean;updatedAt:string|null};
type AcademicImportValues={enabled:boolean;maxCalls:number;concurrency:number;sourceReference:boolean;autoApply:boolean};
type AcademicImportPolicy={values:AcademicImportValues;defaults:AcademicImportValues;customized:boolean;updatedAt:string|null};
const actions=[['define','Define one word'],['explain','Explain'],['eli14','Explain for a 14-year-old'],['ask','Ask / follow-up'],['polish-note','Polish annotation'],['visualize','Structured diagram'],['research','Web research'],['summarize','Summarize'],['tldr','TL;DR'],['compact','Compact note'],['half-page','Half-page summary'],['visual-recap','Visual recap image']] as const;
export const academicImportTasks=[['import-triage','Import triage'],['import-semantic-audit','Semantic audit'],['import-visual-audit','Visual audit'],['import-repair-plan','Repair planning']] as const;
export function isAcademicImportPrompt(key:string):boolean{return key==='system.import-review'||key.startsWith('import.')||key==='contract.import-findings'||key==='contract.import-repairs'}
export function isActiveAcademicImportPrompt(key:string):boolean{return key==='system.import-review'||key==='import.triage'||key==='import.semantic-audit'||key==='import.visual-audit'||key==='import.repair-plan'||key==='contract.import-findings'||key==='contract.import-repairs'}
const taskLabels=Object.fromEntries(actions);

export function SettingsPage({onClose,onLogout}:{onClose:()=>void;onLogout:()=>void}){
 const[tab,setTab]=useState<'prompts'|'models'|'academic'|'advanced'>('prompts'),[models,setModels]=useState<any>(null),[prompts,setPrompts]=useState<Prompt[]|null>(null),[behavior,setBehavior]=useState<Behavior|null>(null),[academicPolicy,setAcademicPolicy]=useState<AcademicImportPolicy|null>(null),[error,setError]=useState('');
 const loadModels=async()=>setModels(await api('/api/settings/models')),loadPrompts=async()=>setPrompts(await api<Prompt[]>('/api/settings/prompts')),loadBehavior=async()=>setBehavior(await api<Behavior>('/api/settings/behavior')),loadAcademicPolicy=async()=>setAcademicPolicy(normalizeAcademicPolicy(await api('/api/settings/academic-import')));
 useEffect(()=>{Promise.all([loadModels(),loadPrompts(),loadBehavior(),loadAcademicPolicy()]).catch(next=>setError((next as Error).message))},[]);
 return <main className="settings-page"><header className="settings-page-header"><div><span className="eyebrow">ProfRead workspace</span><h1>Settings</h1><p>Review the instructions and routing that shape each AI action.</p></div><div className="header-actions"><button className="quiet" onClick={onClose}>Back to library</button><button className="quiet" onClick={onLogout}>Sign out</button></div></header><nav className="settings-tabs" aria-label="Settings sections"><button className={tab==='prompts'?'active':''} onClick={()=>setTab('prompts')}>Action prompts</button><button className={tab==='models'?'active':''} onClick={()=>setTab('models')}>Models & routing</button><button className={tab==='academic'?'active':''} onClick={()=>setTab('academic')}>Academic importer</button><button className={tab==='advanced'?'active':''} onClick={()=>setTab('advanced')}>Context & advanced</button></nav>{error&&<p role="alert" className="error">{error}</p>}{!models||!prompts||!behavior||!academicPolicy?<section className="settings-section"><p>Loading settings…</p></section>:<>{tab==='prompts'&&<ActionPrompts prompts={prompts} routes={models.taskRoutes} models={models.models} onChanged={loadPrompts}/>} {tab==='models'&&<ModelSettings data={models} onChanged={loadModels}/>} {tab==='academic'&&<AcademicImportSettings policy={academicPolicy} models={models} prompts={prompts} onPolicyChanged={loadAcademicPolicy} onModelsChanged={loadModels} onPromptsChanged={loadPrompts}/>} {tab==='advanced'&&<Advanced prompts={prompts} behavior={behavior} onPromptsChanged={loadPrompts} onBehaviorChanged={loadBehavior}/>}</>}</main>
}

function ActionPrompts({prompts,routes,models,onChanged}:{prompts:Prompt[];routes:any[];models:any[];onChanged:()=>Promise<void>}){const routeMap=useMemo(()=>new Map(routes.map(route=>[route.action,route.modelId])),[routes]);return <section className="settings-section"><h2>Action prompts</h2><p>Edit the human-readable request and output contract for each action. Changes apply to the next request.</p><p className="settings-note">Highlight is not listed because it is a local annotation action and does not call an AI model.</p><div className="action-prompt-list">{actions.map(([action,label])=>{const request=prompts.find(prompt=>prompt.key===`request.${action}`),contract=prompts.find(prompt=>prompt.key===`contract.${action}`),model=models.find(item=>item.id===routeMap.get(action));return <article className="action-prompt-group" key={action}><header><div><span className="eyebrow">{action}</span><h3>{label}</h3></div><small>{model?.label??routeMap.get(action)??'No model route'}</small></header>{request?<PromptEditor prompt={request} onChanged={onChanged}/>:<p className="settings-note">The request is the question you type, so this action has only an output contract.</p>}{contract&&<PromptEditor prompt={contract} onChanged={onChanged}/>}</article>})}</div></section>}

function ModelSettings({data,onChanged}:{data:any;onChanged:()=>Promise<void>}){const[status,setStatus]=useState(''),routes=new Map(data.taskRoutes.map((route:any)=>[route.action,route.modelId]));async function saveTask(action:string,modelId:string){try{await api(`/api/settings/tasks/${action}`,{method:'PUT',body:JSON.stringify({modelId})});setStatus(`${taskLabels[action]??action} now uses ${data.models.find((model:any)=>model.id===modelId)?.label??modelId}.`);await onChanged()}catch(error){setStatus((error as Error).message)}}async function saveProvider(provider:any,form:HTMLFormElement){const values=new FormData(form);try{await api(`/api/settings/providers/${provider.id}`,{method:'PUT',body:JSON.stringify({label:values.get('label'),protocol:provider.protocol,baseUrl:values.get('baseUrl'),secretEnvName:values.get('secretEnvName'),enabled:values.get('enabled')==='on',config:JSON.parse(provider.config_json||'{}')})});setStatus('Saved. Provider keys remain server-side environment variables.');await onChanged()}catch(error){setStatus((error as Error).message)}}return <section className="settings-section model-settings"><h2>Model readiness</h2><p>Available models stay selectable during a reading session; the action determines which model runs.</p><div className="model-ready-grid">{data.models.map((model:any)=><article className={`model-ready ${model.ready?'ready':'unavailable'}`} key={model.id}><span>{model.ready?'Ready':'Provider unavailable'}</span><b>{model.label}</b><small>{model.id}</small></article>)}</div><h3>Task routing</h3><p>Choose the default model for each action. The reader toolbar can override one request.</p><div className="task-routing-grid">{actions.map(([action,label])=><label key={action}><span>{label}</span><select value={String(routes.get(action)??'')} onChange={event=>void saveTask(action,event.target.value)}>{data.models.map((model:any)=><option key={model.id} value={model.id}>{model.label}{model.ready?'':' (not ready)'}</option>)}</select></label>)}</div><h3>Providers</h3><p>Configure server-side key references, never secret values.</p>{data.providers.map((provider:any)=><form className="provider-form" key={provider.id} onSubmit={event=>{event.preventDefault();void saveProvider(provider,event.currentTarget)}}><input name="label" defaultValue={provider.label} aria-label="Provider label"/><input name="baseUrl" defaultValue={provider.base_url??''} aria-label="Base URL"/><input name="secretEnvName" defaultValue={provider.secret_env_name} aria-label="Secret environment variable"/><label><input name="enabled" type="checkbox" defaultChecked={Boolean(provider.enabled)}/> Enabled</label><button className="primary">Save</button></form>)}<p role="status">{status}</p></section>}

const academicDefaults:AcademicImportValues={enabled:true,maxCalls:30,concurrency:2,sourceReference:true,autoApply:false};
export function normalizeAcademicPolicy(value:unknown):AcademicImportPolicy{const raw=value&&typeof value==='object'?value as Record<string,any>:{},source=raw.values&&typeof raw.values==='object'?raw.values:raw,defaults=raw.defaults&&typeof raw.defaults==='object'?raw.defaults:academicDefaults;const normalize=(item:Record<string,any>):AcademicImportValues=>({enabled:item.enabled===undefined?true:Boolean(item.enabled),maxCalls:Math.min(40,Math.max(1,Number(item.maxCalls??item.max_calls??30))),concurrency:Math.min(2,Math.max(1,Number(item.concurrency??2))),sourceReference:item.sourceReference===undefined&&item.source_reference===undefined?true:Boolean(item.sourceReference??item.source_reference),autoApply:false});return{values:normalize(source),defaults:normalize(defaults),customized:Boolean(raw.customized),updatedAt:raw.updatedAt??raw.updated_at??null}}

function AcademicImportSettings({policy,models,prompts,onPolicyChanged,onModelsChanged,onPromptsChanged}:{policy:AcademicImportPolicy;models:any;prompts:Prompt[];onPolicyChanged:()=>Promise<void>;onModelsChanged:()=>Promise<void>;onPromptsChanged:()=>Promise<void>}){
 const[status,setStatus]=useState(''),routes=new Map(models.taskRoutes.map((route:any)=>[route.action,route.modelId])),reviewPrompts=prompts.filter(prompt=>isActiveAcademicImportPrompt(prompt.key));
 async function saveTask(action:string,modelId:string){try{await api(`/api/settings/tasks/${action}`,{method:'PUT',body:JSON.stringify({modelId})});setStatus(`${academicImportTasks.find(item=>item[0]===action)?.[1]??action} now uses ${models.models.find((model:any)=>model.id===modelId)?.label??modelId}.`);await onModelsChanged()}catch(error){setStatus((error as Error).message)}}
 return <section className="settings-section academic-import-settings"><h2>Academic importer</h2><p>Deterministic conversion remains authoritative for extraction and safety. These settings control the complementary LLM/VLM review.</p><AcademicPolicyEditor policy={policy} onChanged={onPolicyChanged}/><ReviewerPolicySettings/><h2>Review model routing</h2><p>The importer uses several bounded roles so a fast triage model and a stronger visual reviewer can work in one job.</p><div className="task-routing-grid academic-routing-grid">{academicImportTasks.map(([action,label])=><label key={action}><span>{label}</span><select value={String(routes.get(action)??'')} onChange={event=>void saveTask(action,event.target.value)}><option value="" disabled>Not routed</option>{models.models.map((model:any)=><option key={model.id} value={model.id} disabled={model.ready===false}>{model.label}{model.ready?'':' (not ready)'}</option>)}</select></label>)}</div><p role="status">{status}</p><h2>Import-review prompts</h2><p>Models return structured findings. Editing these instructions cannot expand the repair operations allowed by the server.</p>{reviewPrompts.length===0?<p className="settings-note">Import-review prompt definitions have not been installed yet.</p>:<div className="prompt-template-list academic-prompt-list">{reviewPrompts.map(prompt=><PromptEditor key={prompt.key} prompt={prompt} onChanged={onPromptsChanged}/>)}</div>}</section>
}

function AcademicPolicyEditor({policy,onChanged}:{policy:AcademicImportPolicy;onChanged:()=>Promise<void>}){const[values,setValues]=useState(policy.values),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setValues(policy.values),[policy.values]);const changed=JSON.stringify(values)!==JSON.stringify(policy.values);async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api('/api/settings/academic-import',{method:'PUT',body:JSON.stringify({...values,autoApply:false})});setStatus('Academic import defaults saved.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}async function reset(){setBusy(true);try{await api('/api/settings/academic-import',{method:'DELETE'});setStatus('Reset to source defaults.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}return <form className="academic-policy" onSubmit={save}><header><span className={policy.customized?'overridden':'default'}>{policy.customized?'Customized':'Source defaults'}</span><button type="button" className="quiet" disabled={busy||!policy.customized} onClick={()=>void reset()}>Reset all</button></header><label className="checkbox-field"><input type="checkbox" checked={values.enabled} onChange={event=>setValues(current=>({...current,enabled:event.target.checked}))}/><span><b>Run model-assisted review by default</b><small>A deterministic draft still succeeds when model review is unavailable or incomplete.</small></span></label><div className="academic-policy-grid"><label>Maximum model calls<input type="number" min={1} max={40} value={values.maxCalls} onChange={event=>setValues(current=>({...current,maxCalls:Math.min(40,Math.max(1,Number(event.target.value)))}))}/><small>Hard ceiling per import; normally 12–30.</small></label><label>Concurrent calls<input type="number" min={1} max={2} value={values.concurrency} onChange={event=>setValues(current=>({...current,concurrency:Math.min(2,Math.max(1,Number(event.target.value)))}))}/><small>Keeps API and machine load bounded.</small></label></div><label className="checkbox-field"><input type="checkbox" checked={values.sourceReference} onChange={event=>setValues(current=>({...current,sourceReference:event.target.checked}))}/><span><b>Render source-reference pages</b><small>Compare DOCX, arXiv, PDF, and fetched web-page evidence with the converted reading view when possible.</small></span></label><p className="settings-note">Every repair remains a preview candidate until you explicitly approve selected operations in the import review.</p><footer><button className="primary" disabled={busy||!changed}>Save importer settings</button><span role="status">{status}</span></footer></form>}

function Advanced({prompts,behavior,onPromptsChanged,onBehaviorChanged}:{prompts:Prompt[];behavior:Behavior;onPromptsChanged:()=>Promise<void>;onBehaviorChanged:()=>Promise<void>}){const advanced=prompts.filter(prompt=>!['Action requests','Action contracts'].includes(prompt.category)&&!isAcademicImportPrompt(prompt.key)),categories=[...new Set(advanced.map(prompt=>prompt.category))];return <section className="settings-section"><h2>Context assembly</h2><p>Control when ProfRead sends the whole article, how cached contexts are sized, and how much discussion history is retained.</p><BehaviorEditor settings={behavior} onChanged={onBehaviorChanged}/><h2>Advanced prompt components</h2><p>These templates combine action prompts with article context, repair structured output, and classify free-form questions.</p><div className="prompt-groups">{categories.map(category=><details key={category}><summary><b>{category}</b><span>{advanced.filter(prompt=>prompt.category===category).length} templates</span></summary><div className="prompt-template-list">{advanced.filter(prompt=>prompt.category===category).map(prompt=><PromptEditor key={prompt.key} prompt={prompt} onChanged={onPromptsChanged}/>)}</div></details>)}</div></section>}

function BehaviorEditor({settings,onChanged}:{settings:Behavior;onChanged:()=>Promise<void>}){const[values,setValues]=useState(settings.values),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setValues(settings.values),[settings.values]);async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api('/api/settings/behavior',{method:'PUT',body:JSON.stringify(values)});setStatus('Saved. Cached article contexts will be rebuilt when next needed.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}async function reset(){setBusy(true);try{await api('/api/settings/behavior',{method:'DELETE'});setStatus('Reset to source defaults.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}const changed=settings.definitions.some(item=>values[item.key]!==settings.values[item.key]);return <form className="behavior-settings" onSubmit={save}><header><span className={settings.customized?'overridden':'default'}>{settings.customized?'Customized':'Source defaults'}</span><button type="button" className="quiet" disabled={busy||!settings.customized} onClick={()=>void reset()}>Reset all</button></header><div className="behavior-settings-grid">{settings.definitions.map(item=><label key={item.key}><span>{item.label}</span><small>{item.description}</small><span className="number-field"><input type="number" required min={item.min} max={item.max} step={item.step} value={values[item.key]} onChange={event=>setValues(current=>({...current,[item.key]:Number(event.target.value)}))}/><i>{item.unit}</i></span></label>)}</div><footer><button className="primary" disabled={busy||!changed}>Save context settings</button><span role="status">{status}</span></footer></form>}

function PromptEditor({prompt,onChanged}:{prompt:Prompt;onChanged:()=>Promise<void>}){const[value,setValue]=useState(prompt.template),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setValue(prompt.template),[prompt.template]);async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api(`/api/settings/prompts/${encodeURIComponent(prompt.key)}`,{method:'PUT',body:JSON.stringify({template:value})});setStatus('Saved.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}async function reset(){setBusy(true);try{await api(`/api/settings/prompts/${encodeURIComponent(prompt.key)}`,{method:'DELETE'});setStatus('Reset to source default.');await onChanged()}catch(error){setStatus((error as Error).message)}finally{setBusy(false)}}return <form className="prompt-template" onSubmit={save}><header><div><b>{prompt.label}</b><code>{prompt.key}</code></div><span className={prompt.overridden?'overridden':'default'}>{prompt.overridden?'Customized':'Default'}</span></header><p>{prompt.description}</p>{prompt.variables.length>0&&<small>Variables: {prompt.variables.map(variable=><code key={variable}>{`{{${variable}}}`}</code>)}</small>}<textarea aria-label={`${prompt.label} template`} rows={Math.min(16,Math.max(3,value.split('\n').length+1))} value={value} onChange={event=>setValue(event.target.value)}/><footer><button className="primary" disabled={busy||value===prompt.template}>Save template</button><button type="button" className="quiet" disabled={busy||!prompt.overridden} onClick={()=>void reset()}>Reset to default</button><span role="status">{status}</span></footer></form>}
