import type {FastifyInstance} from 'fastify';import {nanoid} from 'nanoid';import {z} from 'zod';import {visualRecapSchema,diagramSpecSchema} from '@co-reader/shared';import {db,now,row,rows} from '../db/index.js';
const artifactSchema=z.object({documentVersionId:z.string(),kind:z.enum(['tldr','half-page','compact','visual-recap','diagram']),scopeType:z.enum(['document','section','answer','thread']),scopeId:z.string(),content:z.unknown(),sourceRefs:z.array(z.string()).min(1),promoted:z.boolean().default(false)});
function validateContent(kind:string,content:unknown){if(kind==='visual-recap')return visualRecapSchema.parse(content);if(kind==='diagram')return diagramSpecSchema.parse(content);if(typeof content!=='string')throw new Error('Text artifact content must be a string');const words=content.trim().split(/\s+/).filter(Boolean).length;if(kind==='tldr'&&(words>150||(content.match(/^\s*[-*]/gm)??[]).length>5))throw new Error('TL;DR must contain at most five bullets and 150 words');if(kind==='half-page'&&(words<300||words>450))throw new Error('Half-page summary must contain 300 to 450 words');return content;}
export function registerKnowledgeRoutes(app:FastifyInstance):void{
 app.get('/api/documents/:id/artifacts',async request=>rows(`SELECT a.* FROM artifacts a JOIN document_versions v ON v.id=a.document_version_id WHERE v.document_id=? ORDER BY a.created_at DESC`,(request.params as {id:string}).id).map((a:any)=>({...a,content:JSON.parse(a.content_json),sourceRefs:JSON.parse(a.source_refs_json),promoted:Boolean(a.promoted)})));
 app.post('/api/artifacts',async(request,reply)=>{const parsed=artifactSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});let content;try{content=validateContent(parsed.data.kind,parsed.data.content)}catch(error){return reply.code(422).send({error:(error as Error).message})}const version=(row<{next:number}>('SELECT COALESCE(MAX(version),0)+1 next FROM artifacts WHERE kind=? AND scope_type=? AND scope_id=?',parsed.data.kind,parsed.data.scopeType,parsed.data.scopeId)?.next??1),id=nanoid(),time=now();db.prepare('INSERT INTO artifacts(id,document_version_id,kind,version,scope_type,scope_id,content_json,source_refs_json,promoted,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,parsed.data.documentVersionId,parsed.data.kind,version,parsed.data.scopeType,parsed.data.scopeId,JSON.stringify(content),JSON.stringify(parsed.data.sourceRefs),parsed.data.promoted?1:0,time);const documentId=row<{document_id:string}>('SELECT document_id FROM document_versions WHERE id=?',parsed.data.documentVersionId)?.document_id;db.prepare('INSERT INTO search_index(kind,entity_id,document_id,title,body,tags,model_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run('artifact',id,documentId??'',parsed.data.kind,typeof content==='string'?content:JSON.stringify(content),'','',time);return reply.code(201).send({id,version,...parsed.data,content,createdAt:time});});
 app.patch('/api/artifacts/:id/promote',async(request,reply)=>{const parsed=z.object({promoted:z.boolean()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});const result=db.prepare('UPDATE artifacts SET promoted=? WHERE id=?').run(parsed.data.promoted?1:0,(request.params as {id:string}).id);return result.changes?{ok:true}:reply.code(404).send({error:'Artifact not found'});});
 app.get('/api/anchors/repair',async()=>rows(`SELECT a.*,d.id document_id,d.title FROM anchors a JOIN document_versions v ON v.id=a.document_version_id JOIN documents d ON d.id=v.document_id WHERE a.status='unmatched' ORDER BY a.created_at DESC`));
 app.post('/api/anchors/:id/repair',async(request,reply)=>{const parsed=z.object({blockId:z.string(),startOffset:z.number().int().nonnegative(),endOffset:z.number().int().nonnegative(),exactQuote:z.string()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});const anchorId=(request.params as {id:string}).id,block=row<{start_offset:number}>('SELECT b.start_offset FROM blocks b JOIN anchors a ON a.document_version_id=b.document_version_id WHERE a.id=? AND b.id=?',anchorId,parsed.data.blockId);if(!block)return reply.code(404).send({error:'Target block not found'});const result=db.prepare(`UPDATE anchors SET block_id=?,start_offset=?,end_offset=?,exact_quote=?,status='attached' WHERE id=?`).run(parsed.data.blockId,block.start_offset+parsed.data.startOffset,block.start_offset+parsed.data.endOffset,parsed.data.exactQuote,anchorId);return result.changes?{ok:true}:reply.code(404).send({error:'Anchor not found'});});
 app.get('/api/search',async(request,reply)=>{const q=request.query as Record<string,string|undefined>;if(!q.q?.trim())return reply.code(400).send({error:'Search query is required'});const filters:string[]=['search_index MATCH ?'];const params:any[]=[q.q];for(const [key,column] of [['document','document_id'],['type','kind'],['model','model_id']] as const)if(q[key]){filters.push(`${column}=?`);params.push(q[key])}if(q.tag){filters.push('tags LIKE ?');params.push(`%${q.tag}%`)}if(q.from){filters.push('created_at>=?');params.push(q.from)}if(q.to){filters.push('created_at<=?');params.push(q.to)}return rows(`SELECT kind,entity_id,document_id,title,snippet(search_index,4,'<mark>','</mark>','…',24) snippet,tags,model_id,created_at FROM search_index WHERE ${filters.join(' AND ')} ORDER BY rank LIMIT 100`,...params)});
}
