import { chmod, lstat, readdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import type { FastifyInstance } from 'fastify';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { config } from '../config.js';
import { db, now, row, rows } from '../db/index.js';

const nameSchema=z.string().trim().min(1).max(80).transform(value=>value.replace(/\s+/g,' '));
const safeId=(value:string)=>/^[A-Za-z0-9_-]+$/.test(value);
async function makeRemovable(target:string):Promise<void>{try{const stats=await lstat(target);if(!stats.isDirectory())return;await chmod(target,0o700);for(const entry of await readdir(target,{withFileTypes:true}))if(entry.isDirectory()&&!entry.isSymbolicLink())await makeRemovable(join(target,entry.name))}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}}

export function registerLibraryRoutes(app:FastifyInstance):void{
  app.get('/api/groups',async()=>rows(`SELECT g.*,COUNT(d.id) document_count FROM article_groups g LEFT JOIN documents d ON d.group_id=g.id GROUP BY g.id ORDER BY g.name COLLATE NOCASE`));
  app.post('/api/groups',async(request,reply)=>{const parsed=z.object({name:nameSchema}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});const id=nanoid(),time=now();try{db.prepare('INSERT INTO article_groups(id,name,created_at,updated_at)VALUES(?,?,?,?)').run(id,parsed.data.name,time,time);return reply.code(201).send({id,name:parsed.data.name,document_count:0,created_at:time,updated_at:time})}catch{return reply.code(409).send({error:'A group with this name already exists'})}});
  app.patch('/api/groups/:id',async(request,reply)=>{const id=(request.params as{id:string}).id,parsed=z.object({name:nameSchema}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});if(!row('SELECT id FROM article_groups WHERE id=?',id))return reply.code(404).send({error:'Group not found'});try{db.prepare('UPDATE article_groups SET name=?,updated_at=? WHERE id=?').run(parsed.data.name,now(),id);return{ok:true,name:parsed.data.name}}catch{return reply.code(409).send({error:'A group with this name already exists'})}});
  app.delete('/api/groups/:id',async(request,reply)=>{const id=(request.params as{id:string}).id,current=row<{name:string}>('SELECT name FROM article_groups WHERE id=?',id);if(!current)return reply.code(404).send({error:'Group not found'});const count=row<{count:number}>('SELECT COUNT(*) count FROM documents WHERE group_id=?',id)?.count??0;db.prepare('DELETE FROM article_groups WHERE id=?').run(id);return{deleted:true,name:current.name,articlesUngrouped:count}});
  app.put('/api/documents/:id/group',async(request,reply)=>{const documentId=(request.params as{id:string}).id,parsed=z.object({groupId:z.string().nullable()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});if(!row('SELECT id FROM documents WHERE id=?',documentId))return reply.code(404).send({error:'Document not found'});if(parsed.data.groupId&&!row('SELECT id FROM article_groups WHERE id=?',parsed.data.groupId))return reply.code(404).send({error:'Group not found'});db.prepare('UPDATE documents SET group_id=? WHERE id=?').run(parsed.data.groupId,documentId);return{ok:true,groupId:parsed.data.groupId}});
  app.delete('/api/documents/:id',async(request,reply)=>{const documentId=(request.params as{id:string}).id,parsed=z.object({confirmTitle:z.string()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});const document=row<{title:string}>('SELECT title FROM documents WHERE id=?',documentId);if(!document)return reply.code(404).send({error:'Document not found'});if(parsed.data.confirmTitle!==document.title)return reply.code(409).send({error:'The confirmation title does not match the current article title'});
    const importJobs=rows<{id:string;status:string}>('SELECT id,status FROM import_jobs WHERE document_id=? OR target_document_id=?',documentId,documentId),activeImport=importJobs.find(item=>['queued','converting','finalizing'].includes(item.status));
    if(activeImport)return reply.code(409).send({error:'Cancel the active academic import before deleting this article'});
    const versionIds=rows<{id:string}>('SELECT id FROM document_versions WHERE document_id=?',documentId).map(item=>item.id),importJobIds=importJobs.map(item=>item.id);
    if(!safeId(documentId)||versionIds.some(id=>!safeId(id))||importJobIds.some(id=>!safeId(id)))return reply.code(500).send({error:'Stored article identifier is invalid'});
    const modelRunIds=rows<{id:string}>(`SELECT DISTINCT f.model_run_id id FROM import_findings f JOIN import_jobs j ON j.id=f.import_job_id
      WHERE f.model_run_id IS NOT NULL AND (j.document_id=? OR j.target_document_id=?)`,documentId,documentId).map(item=>item.id);
    const generatedIds=new Set<string>();for(const artifact of rows<{content_json:string}>(`SELECT a.content_json FROM artifacts a JOIN document_versions v ON v.id=a.document_version_id WHERE v.document_id=?`,documentId))for(const match of artifact.content_json.matchAll(/\/api\/generated\/([A-Za-z0-9_-]+)\.png/g))generatedIds.add(match[1]!);
    db.exec('BEGIN IMMEDIATE');try{const deleteJob=db.prepare('DELETE FROM import_jobs WHERE id=?');for(const id of importJobIds)deleteJob.run(id);const deleteRun=db.prepare("DELETE FROM model_runs WHERE id=? AND thread_id IS NULL AND action LIKE 'import-%'"),deleteRunsByJob=db.prepare("DELETE FROM model_runs WHERE thread_id IS NULL AND action LIKE 'import-%' AND substr(request_id,1,?)=?");for(const id of modelRunIds)deleteRun.run(id);for(const id of importJobIds){const prefix=`academic:${id}:`;deleteRunsByJob.run(prefix.length,prefix)}db.prepare('DELETE FROM search_index WHERE document_id=?').run(documentId);db.prepare('DELETE FROM documents WHERE id=?').run(documentId);db.exec('COMMIT')}catch(error){db.exec('ROLLBACK');throw error}
    const targets=[...versionIds.flatMap(id=>[join(config.dataDir,'documents',id),join(config.dataDir,'edits',id)]),...importJobIds.map(id=>join(config.dataDir,'imports',id)),join(config.dataDir,'exports',documentId),...[...generatedIds].map(id=>join(config.dataDir,'generated',`${id}.png`))],failures=[] as string[];for(const target of targets)try{await makeRemovable(target);await rm(target,{recursive:true,force:true})}catch(error){request.log.warn({error,target},'Article file cleanup failed');failures.push(target)}
    return{deleted:true,title:document.title,importJobsRemoved:importJobIds.length,cleanupComplete:failures.length===0};
  });
}
