import type { FastifyInstance } from 'fastify';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { db, now, row, rows } from '../db/index.js';

export function registerThreadRoutes(app: FastifyInstance): void {
  app.get('/api/documents/:id/threads', async request => rows(`SELECT t.*,a.block_id,a.exact_quote,a.block_type,
    (SELECT r.action FROM model_runs r WHERE r.thread_id=t.id ORDER BY r.created_at LIMIT 1) action,
    (SELECT json_group_array(json_object('id',m.id,'role',m.role,'content',m.content,'parentMessageId',m.parent_message_id,'createdAt',m.created_at)) FROM messages m WHERE m.thread_id=t.id ORDER BY m.created_at) messages
    FROM threads t LEFT JOIN anchors a ON a.id=t.anchor_id WHERE t.document_id=? ORDER BY t.created_at`,(request.params as {id:string}).id));
  app.post('/api/threads', async (request,reply)=>{const parsed=z.object({documentId:z.string(),anchorId:z.string().optional(),parentMessageId:z.string().optional(),title:z.string().max(240).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});if(!row('SELECT id FROM documents WHERE id=?',parsed.data.documentId))return reply.code(404).send({error:'Document not found'});const id=nanoid(),time=now();db.prepare('INSERT INTO threads (id,document_id,anchor_id,parent_message_id,title,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id,parsed.data.documentId,parsed.data.anchorId??null,parsed.data.parentMessageId??null,parsed.data.title??null,time,time);return reply.code(201).send({id,...parsed.data,createdAt:time,messages:[]});});
  app.post('/api/threads/:id/messages', async (request,reply)=>{const parsed=z.object({role:z.enum(['user','assistant']),content:z.string().min(1).max(100000),parentMessageId:z.string().optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:parsed.error.flatten()});const threadId=(request.params as {id:string}).id;if(!row('SELECT id FROM threads WHERE id=?',threadId))return reply.code(404).send({error:'Thread not found'});const id=nanoid(),time=now();db.prepare('INSERT INTO messages (id,thread_id,parent_message_id,role,content,created_at) VALUES (?,?,?,?,?,?)').run(id,threadId,parsed.data.parentMessageId??null,parsed.data.role,parsed.data.content,time);db.prepare('UPDATE threads SET updated_at=? WHERE id=?').run(time,threadId);if(parsed.data.role==='assistant')db.prepare(`INSERT INTO search_index(kind,entity_id,document_id,title,body,tags,model_id,created_at) SELECT 'answer',?,document_id,'',?,'','',? FROM threads WHERE id=?`).run(id,parsed.data.content,time,threadId);return reply.code(201).send({id,threadId,...parsed.data,createdAt:time});});
}
