import { describe,expect,it,vi } from 'vitest';
import { fetchArxivBundle,fetchArxivPdf,parseArxivReference } from './arxiv.js';

describe('arXiv adapter',()=>{
  it('normalizes modern, legacy, and official URL references',()=>{expect(parseArxivReference('2402.08954v2')).toBe('2402.08954v2');expect(parseArxivReference('hep-th/9901001')).toBe('hep-th/9901001');expect(parseArxivReference('https://arxiv.org/abs/2402.08954')).toBe('2402.08954');expect(()=>parseArxivReference('https://example.test/abs/2402.08954')).toThrow(/arxiv\.org/)});
  it('fetches only bounded arXiv-hosted HTML assets and rewrites them locally',async()=>{const calls:string[]=[];const fetchImpl=vi.fn(async(input:string|URL)=>{const url=String(input);calls.push(url);if(url.endsWith('/html/2402.08954'))return new Response('<html><head><link rel="stylesheet" href="/html/2402.08954/site.css"></head><body><header class="arxiv-html-header">Site chrome</header><article class="ltx_document"><figure><img src="fig.png"><figcaption>Figure 1</figcaption></figure><img src="https://evil.test/x.png"></article><footer>Footer</footer></body></html>',{headers:{'content-type':'text/html'}});if(url.endsWith('site.css'))return new Response('.x{background:url("font.woff2")}@import "https://evil.test/x.css";',{headers:{'content-type':'text/css'}});if(url.endsWith('font.woff2'))return new Response(Buffer.from('font'),{headers:{'content-type':'font/woff2'}});if(url.endsWith('fig.png'))return new Response(Buffer.from([137,80,78,71,13,10,26,10]),{headers:{'content-type':'image/png'}});return new Response('',{status:404})});const bundle=await fetchArxivBundle('2402.08954',{fetchImpl});expect(bundle.html).toMatch(/href="assets\/[a-f0-9]+\.css"/);expect(bundle.html).toMatch(/src="assets\/[a-f0-9]+\.png"/);expect(bundle.html).not.toContain('src="https://evil.test');expect(bundle.html).not.toContain('Site chrome');expect(bundle.html).not.toContain('<footer>');expect(bundle.warnings).toEqual(expect.arrayContaining([expect.objectContaining({code:'source-chrome-removed'})]));expect(bundle.assets).toHaveLength(3);expect(bundle.assets.find(asset=>asset.mimeType==='text/css')?.bytes.toString()).toMatch(/url\("[a-f0-9]+\.woff2"\)/);expect(calls.every(url=>new URL(url).hostname.endsWith('arxiv.org'))).toBe(true)});
  it('rejects redirects away from arXiv',async()=>{const fetchImpl=vi.fn(async()=>new Response(null,{status:302,headers:{location:'https://evil.test/paper'}}));await expect(fetchArxivBundle('2402.08954',{fetchImpl})).rejects.toThrow(/approved HTTPS hosts/)});
  it('validates official PDF reference bytes',async()=>{const fetchImpl=vi.fn(async()=>new Response('%PDF-1.7\n',{headers:{'content-type':'application/pdf'}}));await expect(fetchArxivPdf('https://arxiv.org/pdf/2402.08954.pdf',{fetchImpl})).resolves.toMatchObject({arxivId:'2402.08954'});const invalid=vi.fn(async()=>new Response('<html>no</html>',{headers:{'content-type':'text/html'}}));await expect(fetchArxivPdf('2402.08954',{fetchImpl:invalid})).rejects.toThrow(/text\/html/)});
});
