import {createHash} from 'node:crypto';
import * as cheerio from 'cheerio';
import {PublishedFetchError,validatePublishedUrl,type SafePublishedFetchOptions,type SafePublishedResponse} from './published-fetch.js';
import type {ResolvePublishedSourceOptions} from './published-types.js';

export const sha256=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
const doiSuffix='[-._;()/:a-z0-9+\\[\\]]+';
const completeDoi=new RegExp(`^10\\.\\d{4,9}\\/${doiSuffix}$`,'i');
const embeddedDoi=new RegExp(`10\\.\\d{4,9}\\/${doiSuffix}`,'i');
function cleanDoi(raw:string):string{let value=raw.trim().replace(/^doi:\s*/i,'');while(/[.,;:]$/.test(value))value=value.slice(0,-1);for(const[open,close]of [['(',')'],['[',']']] as const)while(value.endsWith(close)&&value.split(open).length<value.split(close).length)value=value.slice(0,-1);return value.toLowerCase()}
export function extractPublishedDoi(value:string):string|null{let decoded=value;try{decoded=decodeURIComponent(value)}catch{/* retain raw */}const match=decoded.match(embeddedDoi);if(!match)return null;const doi=cleanDoi(match[0]);return completeDoi.test(doi)?doi:null}
function doiResolverUrl(doi:string):URL{return validatePublishedUrl(`https://doi.org/${doi.split('/').map(part=>encodeURIComponent(part)).join('/')}`)}
export function normalizePublishedLocator(value:string):{url:URL;doi:string|null}{const input=value.trim(),bare=input.replace(/^doi:\s*/i,'');if(/^(?:doi:\s*)?10\./i.test(input)){if(!completeDoi.test(bare))throw new PublishedFetchError('Enter a complete DOI using supported printable DOI characters','invalid-url');const doi=bare.toLowerCase();return{url:doiResolverUrl(doi),doi}}return{url:validatePublishedUrl(input),doi:extractPublishedDoi(input)}}
export function cleanPublishedDoi(value:string):string{return cleanDoi(value)}
export function retrievalTime(options:ResolvePublishedSourceOptions):string{return(options.now??(()=>new Date().toISOString()))()}
export function fetchOptions(options:ResolvePublishedSourceOptions,overrides:Pick<SafePublishedFetchOptions,'maxBytes'|'accept'>):SafePublishedFetchOptions{const result:SafePublishedFetchOptions={...overrides};if(options.signal)result.signal=options.signal;if(options.resolver)result.resolver=options.resolver;if(options.transport)result.transport=options.transport;if(options.maxRedirects!==undefined)result.maxRedirects=options.maxRedirects;if(options.timeoutMs!==undefined)result.timeoutMs=options.timeoutMs;if(options.userAgent)result.userAgent=options.userAgent;return result}
export function mimeForPublishedAsset(response:SafePublishedResponse):string|null{const type=response.contentType,bytes=response.bytes,path=new URL(response.finalUrl).pathname.toLowerCase();if(bytes.length>=8&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return'image/png';if(bytes.length>=2&&bytes[0]===0xff&&bytes[1]===0xd8)return'image/jpeg';if(bytes.length>=6&&['GIF87a','GIF89a'].includes(bytes.subarray(0,6).toString('ascii')))return'image/gif';if(bytes.length>=12&&bytes.subarray(0,4).toString('ascii')==='RIFF'&&bytes.subarray(8,12).toString('ascii')==='WEBP')return'image/webp';const sample=bytes.subarray(0,4096).toString('utf8').replace(/^\s*<\?xml[^>]*>/i,'');if((type==='image/svg+xml'||path.endsWith('.svg'))&&/<svg[\s>]/i.test(sample))return'image/svg+xml';if((type==='text/css'||path.endsWith('.css'))&&!bytes.subarray(0,512).includes(0))return'text/css';return null}
export function sanitizePublishedSvg(bytes:Buffer):Buffer|null{try{const $=cheerio.load(bytes.toString('utf8'),{xmlMode:true});if(!$('svg').length)return null;$('script,foreignObject,iframe,object,embed,style').remove();$('*').each((_i,element)=>{const node=$(element);for(const[name,value]of Object.entries(node.attr()??{}))if(/^on/i.test(name)||((name==='href'||name==='xlink:href')&&!String(value).startsWith('#'))||(name==='style'&&/url\s*\(/i.test(String(value))))node.removeAttr(name)});return Buffer.from($.xml())}catch{return null}}
const extensions:Record<string,string>={'image/png':'.png','image/jpeg':'.jpg','image/gif':'.gif','image/webp':'.webp','image/svg+xml':'.svg','text/css':'.css'};
export function publishedAssetPath(url:string,mimeType:string):string{return`assets/${sha256(url).slice(0,24)}${extensions[mimeType]??'.bin'}`}
