import {createHash} from 'node:crypto';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {strToU8,zipSync} from 'fflate';
import {describe,expect,it,vi} from 'vitest';
import {PublishedFetchError,type SafePublishedResponse} from './published-fetch.js';
import {createPublishedSourceHook,resolvePublishedSource,type NormalizedPublishedHtml,type NormalizedPublishedJats} from './published-source.js';

const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]),hash=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
function fetched(url:string,body:string|Buffer,type:string,redirectChain:string[]=[]):SafePublishedResponse{return{requestedUrl:url,finalUrl:url,redirectChain,status:200,headers:new Headers({'content-type':type}),contentType:type,bytes:Buffer.isBuffer(body)?body:Buffer.from(body)}}

describe('published source adapters',()=>{
  it('extracts semantic article HTML, localizes lazy/CDN/CSS assets, and absolutizes citations',async()=>{
    const page='https://publisher.test/paper',html=`<!doctype html><html><head><title>Chrome title</title><meta name="citation_title" content="Complete paper"><meta name="citation_doi" content="10.1234/Test.7"><link rel="canonical" href="${page}"><link rel="stylesheet" href="/paper.css"></head><body><nav>Publisher chrome</nav><main><article><h1>Complete paper</h1><h2>Introduction</h2><p>Complete body text.</p><figure><img data-src="https://cdn.test/figure.png" alt="Result"><figcaption>Figure 1. Result.</figcaption></figure><p><a href="/references/1">Reference 1</a></p><script>steal()</script></article></main></body></html>`;
    const fetcher=vi.fn(async(input:string|URL)=>{const url=String(input);if(url===page)return fetched(url,html,'text/html');if(url==='https://publisher.test/paper.css')return fetched(url,'.paper{background:url("/dot.png")}', 'text/css');if(url==='https://publisher.test/dot.png'||url==='https://cdn.test/figure.png')return fetched(url,png,'image/png');throw new Error(`unexpected ${url}`)}),result=await resolvePublishedSource(page,{fetcher,now:()=> '2026-08-19T00:00:00.000Z'});
    expect(result.kind).toBe('html');if(result.kind!=='html')return;expect(result.title).toBe('Complete paper');expect(result.provenance).toMatchObject({requestedUrl:page,doi:'10.1234/test.7',adapter:'generic-semantic-html'});expect(result.assets.map(asset=>asset.mimeType).sort()).toEqual(['image/png','image/png','text/css']);expect(result.html).toContain('https://publisher.test/references/1');expect(result.html).toMatch(/src="assets\/[a-f0-9]+\.png"/);expect(result.html).not.toContain('steal()');expect(result.assets.find(asset=>asset.mimeType==='text/css')?.bytes.toString()).toMatch(/url\("[a-f0-9]+\.png"\)/);
  });
  it('uses an exact-DOI official OA fallback after a publisher challenge and only resolves bare PMC graphics on the trusted host',async()=>{
    const locator='https://onlinelibrary.wiley.com/doi/10.1515/nanoph-2023-0852',calls:string[]=[],jats='<article><front><article-meta><article-id pub-id-type="doi">10.1515/nanoph-2023-0852</article-id><title-group><article-title>Sample-efficient inverse design</article-title></title-group></article-meta></front><body><sec><title>Introduction</title><p>Full text</p><fig><graphic xlink:href="fig1.png"/></fig><fig><graphic xlink:href="paper/fig1.png"/></fig><fig><graphic xlink:href="fig2.svg"/></fig><fig><graphic xlink:href="../escape.png"/></fig></sec></body></article>';
    const svg=strToU8('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script><rect width="10" height="10"/></svg>'),archive=Buffer.from(zipSync({'paper/fig1.png':png,'fig2.svg':svg,'supplement.pdf':strToU8('%PDF-1.7')})),fetcher=vi.fn(async(input:string|URL)=>{const url=String(input);calls.push(url);if(url===locator)throw new PublishedFetchError('challenge','challenge',403);if(url.startsWith('https://pmc.ncbi.nlm.nih.gov/tools/idconv/'))return fetched(url,JSON.stringify({records:[{doi:'10.1515/nanoph-2023-0852',pmcid:'PMC11636486'}]}),'application/json');if(url.startsWith('https://www.ncbi.nlm.nih.gov/pmc/utils/oa/'))return fetched(url,'<OA><records><record id="PMC11636486" license="CC BY" retracted="no"><link format="tgz" href="ftp://example"/></record></records></OA>','application/xml');if(url.includes('/PMC11636486/fullTextXML'))return fetched(url,jats,'application/xml');if(url.includes('/PMC11636486/supplementaryFiles?includeInlineImage=true'))return fetched(url,archive,'application/zip');throw new Error(`unexpected ${url}`)}),result=await resolvePublishedSource(locator,{fetcher,now:()=> '2026-08-19T00:00:00.000Z'});
    expect(result.kind).toBe('jats');if(result.kind!=='jats')return;expect(result.provenance).toMatchObject({doi:'10.1515/nanoph-2023-0852',pmcid:'PMC11636486',license:'CC BY',adapter:'europe-pmc-jats',directFailure:'challenge'});expect(result.assets).toHaveLength(2);expect(result.assets[0]).toMatchObject({sourceRef:'fig1.png',sourceRefs:['fig1.png','paper/fig1.png'],mimeType:'image/png'});expect(result.assets[0]?.sourceUrl).toContain('/supplementaryFiles?includeInlineImage=true#paper%2Ffig1.png');expect(result.assets[1]).toMatchObject({sourceRef:'fig2.svg',mimeType:'image/svg+xml'});expect(result.assets[1]?.bytes.toString()).not.toContain('<script');expect(result.warnings).toEqual(expect.arrayContaining([expect.objectContaining({code:'unsafe-pmc-graphic'})]));expect(calls.some(url=>url.includes('onlinelibrary.wiley.com'))).toBe(true);
  });
  it('normalizes a direct PDF without interpreting its content as HTML',async()=>{const bytes=Buffer.from('%PDF-1.7\nfixture'),fetcher=vi.fn(async(input:string|URL)=>fetched(String(input),bytes,'application/pdf')),result=await resolvePublishedSource('https://publisher.test/paper.pdf',{fetcher,now:()=> '2026-08-19T00:00:00.000Z'});expect(result).toMatchObject({kind:'pdf',filename:'paper.pdf',provenance:{adapter:'direct-pdf',contentSha256:hash(bytes)}})});
  it('does not accept publisher HTML that identifies a different DOI',async()=>{const locator='https://publisher.test/doi/10.1234/right',html='<html><head><meta name="citation_doi" content="10.1234/wrong"></head><body><article><h1>Wrong paper</h1><h2>Introduction</h2><p>Body</p></article></body></html>',fetcher=vi.fn(async(input:string|URL)=>{const url=String(input);if(url===locator)return fetched(url,html,'text/html');throw new Error('No official match')});await expect(resolvePublishedSource(locator,{fetcher})).rejects.toThrow(/different DOI/)});
});

function job(sourcePath:string,sourceHash:string){return{id:'url-job',source_kind:'url' as const,source_name:'https://publisher.test/paper',source_mime_type:'text/uri-list',source_path:sourcePath,source_hash:sourceHash,companion_pdf_path:null,entry_path:null,status:'queued',ai_review_enabled:0,max_calls:30,review_concurrency:2,auto_apply:0,source_reference:0}}
function workerArchive(sourceHash:string):Buffer{const document=Buffer.from('<!doctype html><html><head><title>Worker title</title></head><body><h1>Worker title</h1><img src="fig1.png"></body></html>'),manifest={schemaVersion:1,operation:'convert',source:{kind:'jats',sha256:sourceHash,pageCount:9,textMode:'native'},converter:{selected:'pandoc-jats'},output:{entryPath:'document.html',title:'Worker title'},warnings:[],files:[{path:'document.html',bytes:document.byteLength,sha256:hash(document)}]};return Buffer.from(zipSync({'document.html':document,'manifest.json':strToU8(JSON.stringify(manifest))}))}

describe('published source hook materialization',()=>{
  it('materializes generic HTML with locator identity and fetched-content provenance',async()=>{const root=await mkdtemp(join(tmpdir(),'afterdraft-url-hook-'));try{const locator='https://publisher.test/paper',sourcePath=join(root,'source.url'),locatorHash=hash(locator);await writeFile(sourcePath,locator);const source:NormalizedPublishedHtml={kind:'html',title:'Published title',html:'<!doctype html><html><head><title>Published title</title></head><body><p>Body</p></body></html>',assets:[],warnings:[],provenance:{requestedUrl:locator,finalUrl:locator,canonicalUrl:locator,redirectChain:[],doi:null,retrievedAt:'2026-08-19T00:00:00.000Z',adapter:'generic-semantic-html',license:null,contentSha256:'b'.repeat(64)}},hook=createPublishedSourceHook({resolve:async()=>source}),bundle=await hook(job(sourcePath,locatorHash),join(root,'bundle'),new AbortController().signal);expect(bundle.manifest.source).toMatchObject({sha256:locatorHash,contentSha256:'b'.repeat(64),contentType:'text/html',assetCount:0,fallbackUsed:false});expect(bundle.manifest.output).toMatchObject({entryPath:'document.html',title:'Published title'})}finally{await rm(root,{recursive:true,force:true})}});
  it('verifies a JATS worker bundle with fetched content hash, then restores locator identity and localizes PMC graphics',async()=>{const root=await mkdtemp(join(tmpdir(),'afterdraft-jats-hook-'));try{const locator='https://publisher.test/doi/10.1234/test',sourcePath=join(root,'source.url'),locatorHash=hash(locator),bytes=Buffer.from('<article><article-id pub-id-type="doi">10.1234/test</article-id></article>'),contentSha256=hash(bytes);await writeFile(sourcePath,locator);const source:NormalizedPublishedJats={kind:'jats',title:'Worker title',bytes,filename:'PMC1.nxml',assets:[{sourceRef:'fig1.png',sourcePath:'assets/fixture.png',sourceUrl:'https://pmc.ncbi.nlm.nih.gov/articles/PMC1/bin/fig1.png',mimeType:'image/png',bytes:png}],warnings:[],provenance:{requestedUrl:locator,finalUrl:'https://www.ebi.ac.uk/europepmc/webservices/rest/PMC1/fullTextXML',canonicalUrl:'https://pmc.ncbi.nlm.nih.gov/articles/PMC1/',redirectChain:[],doi:'10.1234/test',retrievedAt:'2026-08-19T00:00:00.000Z',adapter:'europe-pmc-jats',license:'CC BY',contentSha256,directFailure:'challenge',pmcid:'PMC1'}},converter=vi.fn(async(path:string)=>{expect(hash(await readFile(path))).toBe(contentSha256);return workerArchive(contentSha256)}),hook=createPublishedSourceHook({resolve:async()=>source,convertJats:converter}),bundle=await hook(job(sourcePath,locatorHash),join(root,'bundle'),new AbortController().signal),entry=await readFile(bundle.files.find(file=>file.path==='document.html')!.storagePath,'utf8');expect(converter).toHaveBeenCalledOnce();expect(bundle.manifest.source).toMatchObject({sha256:locatorHash,contentSha256,pageCount:9,textMode:'native',assetCount:1,fallbackUsed:true,pmcid:'PMC1'});expect(bundle.manifest.files.map(file=>file.path)).toContain('assets/fixture.png');expect(entry).toContain('src="assets/fixture.png"')}finally{await rm(root,{recursive:true,force:true})}});
});
