import {basename} from 'node:path';
import * as cheerio from 'cheerio';
import {safePublishedFetch,validatePublishedUrl,type SafePublishedResponse} from './published-fetch.js';
import type {NormalizedPublishedHtml,PublishedSourceAsset,PublishedSourceWarning,ResolvePublishedSourceOptions} from './published-types.js';
import {extractPublishedDoi,fetchOptions,mimeForPublishedAsset,publishedAssetPath,retrievalTime,sanitizePublishedSvg,sha256} from './published-utils.js';

export class PublishedIncompleteError extends Error{constructor(message:string,readonly doi:string|null){super(message)}}
function decode(response:SafePublishedResponse):string{const header=response.headers.get('content-type')??'',declared=header.match(/charset\s*=\s*["']?([^;"'\s]+)/i)?.[1],sample=response.bytes.subarray(0,4096).toString('ascii'),meta=sample.match(/<meta[^>]+charset\s*=\s*["']?([^\s"'/>]+)/i)?.[1];try{return new TextDecoder((declared||meta||'utf-8').toLowerCase()).decode(response.bytes)}catch{return response.bytes.toString('utf8')}}
function meta($:cheerio.CheerioAPI,names:string[]):string{for(const name of names){const escaped=name.replaceAll('"','\\"'),value=$(`meta[name="${escaped}"],meta[property="${escaped}"]`).first().attr('content')?.replace(/\s+/g,' ').trim();if(value)return value}return''}
function jsonDoi($:cheerio.CheerioAPI):string|null{for(const element of $('script[type="application/ld+json"]').toArray())try{const parsed=JSON.parse($(element).text()),queue:unknown[]=Array.isArray(parsed)?parsed:[parsed];while(queue.length){const item=queue.shift();if(!item||typeof item!=='object')continue;const value=item as Record<string,unknown>;for(const key of ['doi','identifier','sameAs','url']){const child=value[key];if(typeof child==='string'){const doi=extractPublishedDoi(child);if(doi)return doi}else if(child&&typeof child==='object')queue.push(child)}if(Array.isArray(value['@graph']))queue.push(...value['@graph'])}}catch{/* ignore malformed metadata */}return null}
function pageDoi($:cheerio.CheerioAPI,fallback:string|null):string|null{return extractPublishedDoi(meta($,['citation_doi','dc.identifier','dc.identifier.doi','prism.doi']))||jsonDoi($)||fallback}
function pageTitle($:cheerio.CheerioAPI):string{return(meta($,['citation_title','dc.title','og:title'])||$('article h1,main h1,h1').first().text()||$('title').first().text()||'Published article').replace(/\s+/g,' ').trim().slice(0,500)}
function canonical($:cheerio.CheerioAPI,base:URL):string{const raw=$('link[rel~="canonical"][href]').first().attr('href');if(!raw)return base.toString();try{return validatePublishedUrl(new URL(raw,base)).toString()}catch{return base.toString()}}
function scopedText(scope:any):string{const visible=scope.clone();visible.find('script,style,noscript,template,form,nav,[hidden],[aria-hidden="true"]').remove();return visible.find('*').addBack().contents().filter((_i:any,node:any)=>node.type==='text').map((_i:any,node:any)=>String(node.data??'')).get().join(' ').replace(/\s+/g,' ').trim()}
function incomplete($:cheerio.CheerioAPI,selected:any):string|null{const pageText=scopedText($('body')),loginForm=$('input[type="password"]').first().closest('form'),loginCopy=`${$('title').first().text()} ${$('h1,h2').first().text()} ${loginForm.text()}`,accessShell=loginForm.length>0&&/\b(?:sign|log)[\s-]*in\b/i.test(loginCopy),explicit=accessShell||/(?:purchase (?:this )?article|rent this article|log in (?:through your institution )?to access|full text (?:is )?(?:unavailable|requires|restricted)|subscribe to (?:read|access)|this is (?:only )?a preview|institutional access required)/i.test(pageText)||$('[class*="paywall"],[id*="paywall"],[class*="access-denied"],[data-paywall]').length>0;if(explicit)return'Publisher supplied an access-controlled or preview-only article shell';const scope=$(selected),text=scopedText(scope),headings=scope.find('h2,h3,[role="heading"]').filter((_i,element)=>/(?:introduction|method|materials|results|discussion|conclusion|references)/i.test($(element).text())).length;return text.length<3500&&/\babstract\b/i.test(text)&&!headings?'Publisher response appears to contain only an abstract':null}
function candidate($:cheerio.CheerioAPI):any{for(const selector of ['article','.article-body,.article__body','[itemtype*="ScholarlyArticle"]','main,[role="main"]']){const nodes=[...new Set($(selector).toArray())];if(nodes.length)return nodes.sort((a,b)=>scopedText($(b)).length-scopedText($(a)).length)[0]}return $('body').get(0)}
function sourceBase($:cheerio.CheerioAPI,finalUrl:URL):URL{const raw=$('base[href]').first().attr('href');if(!raw)return finalUrl;try{return validatePublishedUrl(new URL(raw,finalUrl))}catch{return finalUrl}}
function resource(value:string,base:URL):URL|null{const raw=value.trim();if(!raw||raw.startsWith('#')||/^data:/i.test(raw))return null;try{return validatePublishedUrl(new URL(raw,base))}catch{return null}}
function srcset(value:string):string{return value.split(',').map(item=>item.trim().split(/\s+/,1)[0]??'').filter(Boolean).at(-1)??''}
function links($:cheerio.CheerioAPI,base:URL):void{$('a[href]').each((_i,element)=>{const node=$(element),raw=node.attr('href')??'';if(raw.startsWith('#')||/^mailto:/i.test(raw))return;try{const url=new URL(raw,base);node.attr('href',url.protocol==='https:'?url.toString():'#')}catch{node.attr('href','#')}})}

export async function normalizeGenericPublishedHtml(response:SafePublishedResponse,requestedUrl:string,locatorDoi:string|null,options:ResolvePublishedSourceOptions={}):Promise<NormalizedPublishedHtml>{
  const raw=decode(response),$source=cheerio.load(raw),doi=pageDoi($source,locatorDoi);if(locatorDoi&&doi&&doi!==locatorDoi)throw new PublishedIncompleteError('Publisher page identifies a different DOI',locatorDoi);const selected=candidate($source);if(!selected)throw new PublishedIncompleteError('Publisher page has no article body',doi);const reason=incomplete($source,selected);if(reason)throw new PublishedIncompleteError(reason,doi);
  const finalUrl=new URL(response.finalUrl),base=sourceBase($source,finalUrl),title=pageTitle($source),body=$source.html(selected),$=cheerio.load(`<!doctype html><html><head><title></title></head><body>${body}</body></html>`);$('title').text(title);$('script,noscript,form,button,input,select,textarea,nav').remove();$('[class*="cookie"],[id*="cookie"],[class*="advert"],[id*="advert"],[class*="social-share"],[class*="recommend"],[class*="related-content"],[data-ad]').remove();links($,base);
  const fetcher=options.fetcher??safePublishedFetch,maxAssets=options.maxAssets??240,maxTotal=options.maxTotalBytes??120*1024*1024,warnings:PublishedSourceWarning[]=[],assets:PublishedSourceAsset[]=[],known=new Map<string,PublishedSourceAsset|null>(),inFlight=new Map<string,Promise<PublishedSourceAsset|null>>(),bySourcePath=new Map<string,PublishedSourceAsset>();let total=response.bytes.byteLength;
  async function fetchAsset(url:URL,ancestors:ReadonlySet<string>=new Set()):Promise<PublishedSourceAsset|null>{const key=url.toString();if(known.has(key))return known.get(key)??null;if(ancestors.has(key)){warnings.push({code:'asset-recursion',message:'Skipped a recursive stylesheet asset reference',sourceUrl:key});return null}const active=inFlight.get(key);if(active)return active;if(assets.length>=maxAssets){warnings.push({code:'asset-count-limit',message:`Skipped assets after the ${maxAssets}-file limit`,sourceUrl:key});known.set(key,null);return null}const lineage=new Set(ancestors);lineage.add(key);const task=(async()=>{try{const result=await fetcher(url,fetchOptions(options,{maxBytes:30*1024*1024,accept:'text/css,image/png,image/jpeg,image/gif,image/webp,image/svg+xml;q=0.9,*/*;q=0.1'})),finalKey=result.finalUrl;if(finalKey!==key){if(lineage.has(finalKey)){warnings.push({code:'asset-recursion',message:'Skipped an asset redirect that returned to an active stylesheet',sourceUrl:finalKey});return null}if(known.has(finalKey))return known.get(finalKey)??null;const finalActive=inFlight.get(finalKey);if(finalActive)return finalActive;lineage.add(finalKey)}const mime=mimeForPublishedAsset(result);if(!mime)throw new Error(`unsupported asset content type ${result.contentType||'unknown'}`);if(total+result.bytes.byteLength>maxTotal)throw new Error(`total import exceeds the ${maxTotal} byte limit`);let bytes=result.bytes;if(mime==='image/svg+xml'){const safe=sanitizePublishedSvg(bytes);if(!safe)throw new Error('invalid SVG asset');bytes=safe}if(mime==='text/css')bytes=Buffer.from(await rewriteCss(bytes.toString('utf8'),new URL(result.finalUrl),lineage));if(total+bytes.byteLength>maxTotal)throw new Error(`total import exceeds the ${maxTotal} byte limit`);const sourcePath=publishedAssetPath(result.finalUrl,mime),stored=bySourcePath.get(sourcePath);if(stored){if(stored.mimeType!==mime||!stored.bytes.equals(bytes))throw new Error(`asset path collision for ${sourcePath}`);known.set(finalKey,stored);return stored}total+=bytes.byteLength;const asset={sourcePath,sourceUrl:result.finalUrl,mimeType:mime,bytes};known.set(finalKey,asset);bySourcePath.set(sourcePath,asset);assets.push(asset);return asset}catch(error){if(options.signal?.aborted)throw options.signal.reason??error;warnings.push({code:'asset-fetch-failed',message:error instanceof Error?error.message:String(error),sourceUrl:key});return null}})();inFlight.set(key,task);try{const asset=await task;known.set(key,asset);return asset}finally{if(inFlight.get(key)===task)inFlight.delete(key)}}
  async function rewriteCss(css:string,cssBase:URL,ancestors:ReadonlySet<string>):Promise<string>{const stripped=css.replace(/@import[\s\S]*?(?:;|$)/gi,''),values=[...stripped.matchAll(/url\(\s*(['"]?)(.*?)\1\s*\)/gi)].map(match=>match[2]??''),replacements=new Map<string,string>();for(const value of values){const url=resource(value,cssBase);if(!url){replacements.set(value,'');continue}const asset=await fetchAsset(url,ancestors);replacements.set(value,asset?basename(asset.sourcePath):'')}return stripped.replace(/url\(\s*(['"]?)(.*?)\1\s*\)/gi,(_all,_quote,value:string)=>`url("${replacements.get(value)??''}")`)}
  const styles=$source('link[rel~="stylesheet"][href]').toArray().slice(0,12);for(const element of styles){const url=resource($source(element).attr('href')??'',base);if(!url)continue;const asset=await fetchAsset(url);if(asset?.mimeType==='text/css')$('head').append(`<link rel="stylesheet" href="${asset.sourcePath}">`)}
  const references:Array<{element:any;raw:string}>=[];$('img,source').each((_i,element)=>{const node=$(element),rawValue=node.attr('data-src')||node.attr('data-original')||node.attr('data-lazy-src')||node.attr('src')||srcset(node.attr('data-srcset')||node.attr('srcset')||'');if(rawValue&&!/^data:/i.test(rawValue))references.push({element,raw:rawValue});node.removeAttr('data-src').removeAttr('data-original').removeAttr('data-lazy-src').removeAttr('data-srcset').removeAttr('srcset')});for(const item of references){const node=$(item.element),url=resource(item.raw,base);if(!url){node.attr('src','');warnings.push({code:'unsafe-asset-url',message:'Removed a non-HTTPS or unsafe article asset',sourceUrl:item.raw});continue}const asset=await fetchAsset(url);node.attr('src',asset?.sourcePath??'')}
  const canonicalUrl=canonical($source,finalUrl),license=meta($source,['citation_license','dc.rights','dcterms.rights','license'])||null;return{kind:'html',title,html:$.html(),assets,warnings,provenance:{requestedUrl,finalUrl:response.finalUrl,canonicalUrl,redirectChain:response.redirectChain,doi,retrievedAt:retrievalTime(options),adapter:'generic-semantic-html',license,contentSha256:sha256(response.bytes)}};
}
