import * as cheerio from 'cheerio';
import {safePublishedFetch} from './published-fetch.js';
import {matchPublishedArchiveEntry,readPublishedArchiveAssets} from './published-archive.js';
import type {NormalizedPublishedJats,PublishedSourceAsset,PublishedSourceWarning,ResolvePublishedSourceOptions} from './published-types.js';
import {cleanPublishedDoi,extractPublishedDoi,fetchOptions,mimeForPublishedAsset,publishedAssetPath,retrievalTime,sanitizePublishedSvg,sha256} from './published-utils.js';

async function json(url:URL,options:ResolvePublishedSourceOptions):Promise<unknown>{const fetcher=options.fetcher??safePublishedFetch,response=await fetcher(url,fetchOptions(options,{maxBytes:2*1024*1024,accept:'application/json'}));return JSON.parse(response.bytes.toString('utf8'))}
function optionalFailure(error:unknown,options:ResolvePublishedSourceOptions):null{if(options.signal?.aborted)throw options.signal.reason??error;return null}
async function idConverter(doi:string,options:ResolvePublishedSourceOptions):Promise<string|null>{try{const url=new URL('https://pmc.ncbi.nlm.nih.gov/tools/idconv/api/v1/articles/');url.searchParams.set('ids',doi);url.searchParams.set('idtype','doi');url.searchParams.set('format','json');url.searchParams.set('tool','AfterDraft');if(options.contactEmail)url.searchParams.set('email',options.contactEmail);const value=await json(url,options) as{records?:Array<{doi?:unknown;pmcid?:unknown}>},record=value.records?.find(item=>typeof item.doi==='string'&&cleanPublishedDoi(item.doi)===doi);return record&&typeof record.pmcid==='string'&&/^PMC\d+$/.test(record.pmcid)?record.pmcid:null}catch(error){return optionalFailure(error,options)}}
async function europeSearch(doi:string,options:ResolvePublishedSourceOptions):Promise<string|null>{try{const url=new URL('https://www.ebi.ac.uk/europepmc/webservices/rest/search');url.searchParams.set('query',`DOI:${doi}`);url.searchParams.set('format','json');const value=await json(url,options) as{resultList?:{result?:Array<{doi?:unknown;pmcid?:unknown}>}},record=value.resultList?.result?.find(item=>typeof item.doi==='string'&&cleanPublishedDoi(item.doi)===doi);return record&&typeof record.pmcid==='string'&&/^PMC\d+$/.test(record.pmcid)?record.pmcid:null}catch(error){return optionalFailure(error,options)}}
async function oaLicense(pmcid:string,options:ResolvePublishedSourceOptions):Promise<string|null>{try{const fetcher=options.fetcher??safePublishedFetch,url=new URL('https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi');url.searchParams.set('id',pmcid);const response=await fetcher(url,fetchOptions(options,{maxBytes:1024*1024,accept:'application/xml,text/xml'})),$=cheerio.load(response.bytes.toString('utf8'),{xmlMode:true}),record=$(`record[id="${pmcid}"]`).first();if(!record.length||record.attr('retracted')==='yes'||!record.find('link[format="tgz"]').length)return null;return record.attr('license')?.trim()||'Open Access'}catch(error){return optionalFailure(error,options)}}
function doiFromJats(bytes:Buffer):string|null{const $=cheerio.load(bytes.toString('utf8'),{xmlMode:true});return extractPublishedDoi($('article-id[pub-id-type="doi"]').first().text())}

export async function findOfficialPmcJats(doi:string,requestedUrl:string,directFailure:string,options:ResolvePublishedSourceOptions={}):Promise<NormalizedPublishedJats|null>{
  const pmcid=await idConverter(doi,options)??await europeSearch(doi,options);if(!pmcid)return null;const license=await oaLicense(pmcid,options);if(!license)return null;const fetcher=options.fetcher??safePublishedFetch,jatsUrl=`https://www.ebi.ac.uk/europepmc/webservices/rest/${pmcid}/fullTextXML`,response=await fetcher(jatsUrl,fetchOptions(options,{maxBytes:20*1024*1024,accept:'application/xml,text/xml'}));if(!/<article(?:\s|>)/i.test(response.bytes.subarray(0,128*1024).toString('utf8'))||doiFromJats(response.bytes)!==doi)throw new Error('Official repository returned a different or invalid JATS article');
  const $=cheerio.load(response.bytes.toString('utf8'),{xmlMode:true}),title=$('article-title').first().text().replace(/\s+/g,' ').trim().slice(0,500)||doi,warnings:PublishedSourceWarning[]=[],assets:PublishedSourceAsset[]=[],seen=new Set<string>(),references:string[]=[],maxAssets=options.maxAssets??240,maxTotal=options.maxTotalBytes??120*1024*1024;let total=response.bytes.byteLength;
  for(const element of $('graphic,inline-graphic').toArray()){
    const raw=$(element).attr('xlink:href')||$(element).attr('href')||'';if(!raw||seen.has(raw))continue;seen.add(raw);if(references.length>=maxAssets){warnings.push({code:'asset-count-limit',message:`Skipped PMC graphics after the ${maxAssets}-file limit`});break}references.push(raw)
  }
  if(references.length){
    const archiveUrl=`https://www.ebi.ac.uk/europepmc/webservices/rest/${pmcid}/supplementaryFiles?includeInlineImage=true`;
    try{
      const archive=await fetcher(archiveUrl,fetchOptions(options,{maxBytes:Math.max(1,maxTotal-total),accept:'application/zip,application/octet-stream'})),selected=await readPublishedArchiveAssets(archive.bytes,references,{maxExpandedBytes:maxTotal}),unsafe=new Set(selected.unsafeReferences),byEntry=new Map<string,PublishedSourceAsset>();
      for(const raw of references){
        if(unsafe.has(raw)){warnings.push({code:'unsafe-pmc-graphic',message:'Skipped a non-local PMC graphic reference',sourceUrl:raw});continue}
        const entry=matchPublishedArchiveEntry(raw,selected.entries);if(!entry){warnings.push({code:'pmc-graphic-missing',message:'The official repository asset archive did not contain a uniquely matching graphic',sourceUrl:raw});continue}
        const existing=byEntry.get(entry.path);if(existing){existing.sourceRefs=[...new Set([...(existing.sourceRefs??[]),raw])];continue}
        const sourceUrl=`${archive.finalUrl}#${encodeURIComponent(entry.path)}`,assetResponse={...archive,finalUrl:sourceUrl,contentType:/\.svg$/i.test(entry.path)?'image/svg+xml':'',bytes:entry.bytes},mime=mimeForPublishedAsset(assetResponse);if(!mime||mime==='text/css'){warnings.push({code:'pmc-graphic-invalid',message:'The official repository graphic had an unsupported or invalid file signature',sourceUrl:raw});continue}
        let bytes=entry.bytes;if(mime==='image/svg+xml'){const safe=sanitizePublishedSvg(bytes);if(!safe){warnings.push({code:'pmc-graphic-invalid',message:'The official repository SVG could not be sanitized',sourceUrl:raw});continue}bytes=safe}
        if(total+bytes.byteLength>maxTotal){warnings.push({code:'asset-total-limit',message:`Skipped PMC graphics after the ${maxTotal} byte total limit`,sourceUrl:raw});break}total+=bytes.byteLength;const asset={sourceRef:raw,sourceRefs:[raw],sourcePath:publishedAssetPath(sourceUrl,mime),sourceUrl,mimeType:mime,bytes};byEntry.set(entry.path,asset);assets.push(asset);
      }
    }catch(error){if(options.signal?.aborted)throw options.signal.reason??error;warnings.push({code:'pmc-graphic-archive-failed',message:error instanceof Error?error.message:String(error),sourceUrl:archiveUrl})}
  }
  return{kind:'jats',title,bytes:response.bytes,filename:`${pmcid}.nxml`,assets,warnings,provenance:{requestedUrl,finalUrl:response.finalUrl,canonicalUrl:`https://pmc.ncbi.nlm.nih.gov/articles/${pmcid}/`,redirectChain:response.redirectChain,doi,retrievedAt:retrievalTime(options),adapter:'europe-pmc-jats',license,contentSha256:sha256(response.bytes),directFailure,pmcid}};
}
