import {readFile} from 'node:fs/promises';import * as cheerio from 'cheerio';import PDFDocument from 'pdfkit';import {row,rows} from '../db/index.js';
interface ExportData{title:string;sourceName:string;html:string;highlights:any[];artifacts:any[];messages:any[]}
interface StoredAsset{id:string;mime_type:string;storage_path:string}

export async function embedDocumentAssets(html:string,versionId:string,assets:StoredAsset[]):Promise<string>{
  const content=new Map<string,Buffer>();
  for(const asset of assets)content.set(asset.id,await readFile(asset.storage_path));
  const dataUrls=new Map<string,string>();
  for(const asset of assets)if(asset.mime_type!=='text/css')dataUrls.set(asset.id,`data:${asset.mime_type};base64,${content.get(asset.id)!.toString('base64')}`);
  for(const asset of assets)if(asset.mime_type==='text/css'){
    let stylesheet=content.get(asset.id)!.toString('utf8');
    for(const [assetId,dataUrl] of dataUrls)stylesheet=stylesheet.replaceAll(`/api/assets/${versionId}/${assetId}`,dataUrl);
    dataUrls.set(asset.id,`data:text/css;base64,${Buffer.from(stylesheet).toString('base64')}`);
  }
  for(const [assetId,dataUrl] of dataUrls)html=html.replaceAll(`/api/assets/${versionId}/${assetId}`,dataUrl);
  return html;
}

export async function exportData(documentId:string,fullTranscript:boolean):Promise<ExportData>{const version=row<any>(`SELECT d.title,v.id,v.source_name,v.sanitized_html_path FROM documents d JOIN document_versions v ON v.document_id=d.id WHERE d.id=? ORDER BY v.version DESC LIMIT 1`,documentId);if(!version)throw new Error('Document not found');let html=await readFile(version.sanitized_html_path,'utf8');const assets=rows<StoredAsset>('SELECT id,mime_type,storage_path FROM assets WHERE document_version_id=?',version.id);html=await embedDocumentAssets(html,version.id,assets);html=html.replace(/<script[^>]*>[^]*?<\/script>/gi,'');const highlights=rows<any>(`SELECT h.*,a.exact_quote,a.block_id FROM highlights h JOIN anchors a ON a.id=h.anchor_id WHERE a.document_version_id=? AND h.checked=1 ORDER BY a.start_offset`,version.id),artifacts=rows<any>(`SELECT * FROM artifacts WHERE document_version_id=? AND promoted=1 ORDER BY created_at`,version.id).map(a=>({...a,content:JSON.parse(a.content_json),sourceRefs:JSON.parse(a.source_refs_json)})),messages=fullTranscript?rows<any>(`SELECT m.* FROM messages m JOIN threads t ON t.id=m.thread_id WHERE t.document_id=? ORDER BY m.created_at`,documentId):[];return{title:version.title,sourceName:version.source_name,html,highlights,artifacts,messages}}
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function renderHtml(data:ExportData):string{const $=cheerio.load(data.html);for(const highlight of data.highlights){const target=$(`[data-block-id="${highlight.block_id}"]`).first();if(!target.length)continue;target.addClass('co-reader-highlight');if(highlight.note&&highlight.note.length<=400)target.attr('data-note',highlight.note).attr('tabindex','0');}const footnotes=data.highlights.filter(h=>h.note&&h.note.length>400&&h.note.length<=1200),appendix=[...data.highlights.filter(h=>h.note&&h.note.length>1200).map(h=>({title:h.exact_quote,content:h.note})),...data.artifacts.map(a=>({title:a.kind,content:typeof a.content==='string'?a.content:JSON.stringify(a.content,null,2)}))];$('head').append(`<style>.co-reader-highlight{background:#ffe58a}.co-reader-highlight[data-note]{text-decoration:underline dotted;cursor:help}.co-reader-highlight[data-note]:focus:after,.co-reader-highlight[data-note]:hover:after{content:attr(data-note);position:absolute;max-width:26rem;background:#222;color:#fff;padding:.7rem;z-index:3}.export-notes{max-width:760px;margin:3rem auto;padding:1rem}</style>`);$('body').append(`<section class="export-notes"><h2>Study notes</h2>${footnotes.map((n,i)=>`<p><sup>${i+1}</sup> ${escape(n.note)}</p>`).join('')}${appendix.length?`<h2>Appendix</h2>${appendix.map(a=>`<article><h3>${escape(a.title)}</h3><pre>${escape(a.content)}</pre></article>`).join('')}`:''}${data.messages.length?`<h2>Full discussion</h2>${data.messages.map(m=>`<p><strong>${escape(m.role)}:</strong> ${escape(m.content)}</p>`).join('')}`:''}</section>`);return '<!doctype html>'+$.html()}
export function renderMarkdown(data:ExportData):string{const lines=[`# ${data.title}`,'',`Source: ${data.sourceName}`,'','## Checked highlights',''];data.highlights.forEach((h,i)=>{lines.push(`> ${h.exact_quote}[^${i+1}]`,'')});if(data.artifacts.length)lines.push('## Promoted artifacts','',...data.artifacts.flatMap(a=>[`### ${a.kind}`,typeof a.content==='string'?a.content:'```json\n'+JSON.stringify(a.content,null,2)+'\n```','',`Sources: ${a.sourceRefs.join(', ')}`,'']));if(data.messages.length)lines.push('## Discussion appendix','',...data.messages.flatMap(m=>[`**${m.role}:** ${m.content}`,'']));data.highlights.forEach((h,i)=>lines.push(`[^${i+1}]: ${h.note||'Checked passage from the source article.'}`));return lines.join('\n')}
export async function renderPdf(data:ExportData):Promise<Buffer>{return await new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:54,info:{Title:data.title}}),chunks:Buffer[]=[];doc.on('data',(c:Buffer)=>chunks.push(c));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.fontSize(24).text(data.title).moveDown(.3).fontSize(9).fillColor('#666').text(`Source: ${data.sourceName}`).moveDown(2);doc.fillColor('#222').fontSize(16).text('Checked highlights').moveDown();for(const [i,h] of data.highlights.entries()){doc.fontSize(11).text(`${i+1}. “${h.exact_quote}”`,{continued:false}).fontSize(9).fillColor('#555').text(h.note||'').fillColor('#222').moveDown()}for(const a of data.artifacts){doc.addPage();if(a.kind==='visual-recap'&&typeof a.content==='object'){const recap=a.content;doc.fontSize(19).text(recap.title??'Visual recap').fontSize(10).fillColor('#555').text(recap.thesis??'').fillColor('#222').moveDown(.5);for(const section of recap.sections??[])doc.fontSize(11).text(section.title).fontSize(8).text(String(section.summary).slice(0,360)).moveDown(.35);doc.fontSize(11).text('Takeaways').fontSize(8).list((recap.takeaways??[]).map((item:string)=>item.slice(0,180)));doc.fontSize(7).fillColor('#666').text(`Sources: ${a.sourceRefs.join(', ')}`,54,780,{width:487,height:20,ellipsis:true})}else{doc.fontSize(18).text(String(a.kind)).moveDown();doc.fontSize(10).text(typeof a.content==='string'?a.content:JSON.stringify(a.content,null,2));doc.moveDown().fontSize(8).fillColor('#666').text(`Sources: ${a.sourceRefs.join(', ')}`).fillColor('#222')}}if(data.messages.length){doc.addPage().fontSize(18).text('Discussion appendix').moveDown();for(const m of data.messages)doc.fontSize(9).text(`${m.role}: ${m.content}`).moveDown()}doc.end()})}
