import{randomUUID}from'node:crypto';import{readFile}from'node:fs/promises';import{describe,expect,it}from'vitest';import type{WriterEditOperation}from'@afterdraft/shared';import{db,now,row}from'../db/index.js';import{importSource}from'../ingest/index.js';import{editHistory,restoreEdit,saveEdits,saveWriterEdits}from'./index.js';import{effectiveVersion}from'./effective.js';

describe('restricted document editing',()=>{it('saves atomic revisions, refreshes derived state, and restores the original',async()=>{
  const marker=randomUUID(),sourceTitle=`Edit source ${marker}`,imported=await importSource({buffer:Buffer.from(`<title>${sourceTitle}</title><h1>Original heading</h1><p>Alpha <em>stable</em> omega</p><p>Anchor phrase ${marker}</p><h2>Folded topic</h2><p>Section body</p><figure><img alt="Topology"><figcaption>Old caption</figcaption></figure><table><tr><td>Value</td></tr></table><video controls aria-label="Demonstration"></video>`),filename:'editable.html',mimeType:'text/html'});if(!imported.versionId||!imported.documentId)throw new Error('Import failed');
  const versionId=imported.versionId,text=row<any>('SELECT id,text_content,start_offset,end_offset FROM blocks WHERE document_version_id=? AND text_content=?',versionId,`Anchor phrase ${marker}`)!,first=row<any>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Alpha stable omega')!,heading=row<any>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Original heading')!,section=row<any>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Folded topic')!,figure=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='diagram'",versionId)!,image=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='image'",versionId)!,table=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='table'",versionId)!,video=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='video'",versionId)!;
  const anchor=randomUUID(),time=now();db.prepare('INSERT INTO anchors(id,document_version_id,block_id,exact_quote,prefix_text,suffix_text,start_offset,end_offset,block_type,created_at)VALUES(?,?,?,?,?,?,?,?,?,?)').run(anchor,versionId,text.id,text.text_content,'','',text.start_offset,text.end_offset,'text',time);
  const saved=await saveEdits(versionId,0,[{type:'replace-text',blockId:heading.id,text:'Renamed heading'},{type:'replace-text',blockId:first.id,text:'Alpha stable revised omega'},{type:'format-text',blockId:first.id,startOffset:0,endOffset:5,style:'italic',enabled:true},{type:'format-text',blockId:first.id,startOffset:6,endOffset:12,style:'bold',enabled:true},{type:'format-text',blockId:first.id,startOffset:21,endOffset:26,style:'underline',enabled:true},{type:'replace-text',blockId:text.id,text:'Completely different sentence'},{type:'fold-section',blockId:section.id,folded:true},{type:'resize-image',blockId:image.id,width:640},{type:'set-caption',blockId:figure.id,label:'Diagram',number:'3a',caption:'Memory topology'},{type:'set-caption',blockId:table.id,label:'Table',number:'2',caption:'Recorded value'},{type:'set-caption',blockId:video.id,label:'Video',number:'1',caption:'Playback overview'}]);
  expect(saved).toMatchObject({revision:1,title:'Renamed heading'});const effective=effectiveVersion(versionId)!,html=await readFile(effective.htmlPath,'utf8');expect(html.match(/<!doctype/gi)).toHaveLength(1);expect(html).toContain('data-afterdraft-section');expect(html).not.toMatch(/<details[^>]* open/);expect(html).toContain('data-afterdraft-caption-number=""');expect(html).toContain('Memory topology');expect(html).toContain('Recorded value');expect(html).toContain('width="640"');expect(html).toContain('width:640px!important;height:auto!important');expect(html).toContain('data-afterdraft-format="bold"');expect(html).toContain('data-afterdraft-format="italic"');expect(html).toContain('data-afterdraft-format="underline"');expect(html).toMatch(/<em><strong[^>]*>stable<\/strong><\/em>/);expect(html).toMatch(/<\/details><script/);expect(row<{title:string}>('SELECT title FROM documents WHERE id=?',imported.documentId)?.title).toBe('Renamed heading');expect(row<{status:string}>('SELECT status FROM anchors WHERE id=?',anchor)?.status).toBe('unmatched');expect(row<{body:string}>('SELECT body FROM search_index WHERE kind=\'article\' AND entity_id=?',versionId)?.body).toContain('Completely different sentence');expect(editHistory(versionId).currentRevision).toBe(1);
  await expect(saveEdits(versionId,0,[{type:'replace-text',blockId:heading.id,text:'Stale'}])).rejects.toMatchObject({statusCode:409});const restored=await restoreEdit(versionId,0,1);expect(restored).toMatchObject({revision:2,title:sourceTitle});const original=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8');expect(original).not.toContain('<details data-afterdraft-section');expect(original).not.toContain('Memory topology');expect(row<{title:string}>('SELECT title FROM documents WHERE id=?',imported.documentId)?.title).toBe(sourceTitle);expect(editHistory(versionId).revisions[0]).toMatchObject({revision:2,restored_from_revision:0});
})});

describe('Writer document editing',()=>{
  it('applies safe replace/insert/delete operations as one attributed revision',async()=>{
    const marker=randomUUID(),imported=await importSource({buffer:Buffer.from(`<title>Writer ${marker}</title><h1>Primary heading</h1><p>Old explanation</p><p>Duplicate paragraph</p><p>Media paragraph <img alt="Retained diagram"></p>`),filename:'writer.html',mimeType:'text/html'});if(!imported.versionId)throw new Error('Import failed');const versionId=imported.versionId;
    const old=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Old explanation')!,duplicate=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Duplicate paragraph')!,heading=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Primary heading')!,image=row<{id:string}>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='image'",versionId)!;
    const operations:WriterEditOperation[]=[{type:'replace-text',blockId:old.id,text:'Revised explanation'},{type:'insert-text-block',blockId:old.id,position:'after',tag:'p',text:'Literal <script>alert(1)</script> explanation'},{type:'delete-text-block',blockId:duplicate.id}];
    const saved=await saveWriterEdits(versionId,0,operations,'proposal-safe');expect(saved).toMatchObject({revision:1,originType:'writer-proposal',originId:'proposal-safe'});
    const html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8');expect(html).toContain('Revised explanation');expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');expect(html).not.toContain('<script>alert(1)</script>');expect(html).not.toContain('Duplicate paragraph');expect(html).toContain('Retained diagram');
    expect(row<{origin_type:string;origin_id:string}>('SELECT origin_type,origin_id FROM document_edit_revisions WHERE document_version_id=? AND revision=1',versionId)).toEqual({origin_type:'writer-proposal',origin_id:'proposal-safe'});
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:old.id,text:'Again'}],'proposal-safe')).rejects.toMatchObject({statusCode:409});
    await expect(saveWriterEdits(versionId,1,[{type:'delete-text-block',blockId:heading.id}],'delete-heading')).rejects.toThrow('primary document heading');
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:heading.id,text:'   '}],'blank-heading')).rejects.toThrow('primary document heading');
    await expect(saveWriterEdits(versionId,1,[{type:'delete-text-block',blockId:image.id}],'delete-media')).rejects.toThrow('Only text blocks');
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:old.id,text:'Revised explanation'}],'noop')).rejects.toThrow('no-op');
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:old.id,text:'First'},{type:'replace-text',blockId:old.id,text:'Second'}],'conflict')).rejects.toThrow('more than once');
    expect(editHistory(versionId).currentRevision).toBe(1);
  });

  it('serializes competing revision writers and leaves one consistent winner',async()=>{
    const marker=randomUUID(),imported=await importSource({buffer:Buffer.from(`<title>Writer race ${marker}</title><h1>Race</h1><p>Original race text</p>`),filename:'race.html',mimeType:'text/html'});if(!imported.versionId)throw new Error('Import failed');const versionId=imported.versionId,block=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Original race text')!;
    const results=await Promise.allSettled([saveWriterEdits(versionId,0,[{type:'replace-text',blockId:block.id,text:'Writer winner'}],'proposal-race'),saveEdits(versionId,0,[{type:'replace-text',blockId:block.id,text:'Manual winner'}])]);
    expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);const rejected=results.find(result=>result.status==='rejected') as PromiseRejectedResult;expect(rejected.reason).toMatchObject({statusCode:409});expect(editHistory(versionId).currentRevision).toBe(1);
    const html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8'),hasWriter=html.includes('Writer winner'),hasManual=html.includes('Manual winner');expect(hasWriter||hasManual).toBe(true);expect(hasWriter&&hasManual).toBe(false);
  });
});
