import{randomUUID}from'node:crypto';import{readFile}from'node:fs/promises';import{describe,expect,it}from'vitest';import type{WriterEditOperation}from'@afterdraft/shared';import{db,now,row}from'../db/index.js';import{importSource}from'../ingest/index.js';import{editHistory,restoreEdit,saveEdits,saveWriterEdits}from'./index.js';import{effectiveVersion}from'./effective.js';
import*as cheerio from'cheerio';

describe('restricted document editing',()=>{it('saves atomic revisions, refreshes derived state, and restores the original',async()=>{
  const marker=randomUUID(),sourceTitle=`Edit source ${marker}`,imported=await importSource({buffer:Buffer.from(`<title>${sourceTitle}</title><h1>Original heading</h1><p>Alpha <em>stable</em> omega</p><p>Anchor phrase ${marker}</p><h2>Folded topic</h2><p>Section body</p><figure><img alt="Topology"><figcaption>Old caption</figcaption></figure><table><tr><td>Value</td></tr></table><video controls aria-label="Demonstration"></video>`),filename:'editable.html',mimeType:'text/html'});if(!imported.versionId||!imported.documentId)throw new Error('Import failed');
  const versionId=imported.versionId,text=row<any>('SELECT id,text_content,start_offset,end_offset FROM blocks WHERE document_version_id=? AND text_content=?',versionId,`Anchor phrase ${marker}`)!,first=row<any>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Alpha stable omega')!,heading=row<any>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Original heading')!,section=row<any>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Folded topic')!,figure=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='diagram'",versionId)!,image=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='image'",versionId)!,table=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='table'",versionId)!,video=row<any>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='video'",versionId)!;
  const anchor=randomUUID(),time=now();db.prepare('INSERT INTO anchors(id,document_version_id,block_id,exact_quote,prefix_text,suffix_text,start_offset,end_offset,block_type,created_at)VALUES(?,?,?,?,?,?,?,?,?,?)').run(anchor,versionId,text.id,text.text_content,'','',text.start_offset,text.end_offset,'text',time);
  const saved=await saveEdits(versionId,0,[{type:'replace-text',blockId:heading.id,text:'Renamed heading'},{type:'replace-text',blockId:first.id,text:'Alpha stable revised omega'},{type:'format-text',blockId:first.id,startOffset:0,endOffset:5,style:'italic',enabled:true},{type:'format-text',blockId:first.id,startOffset:6,endOffset:12,style:'bold',enabled:true},{type:'format-text',blockId:first.id,startOffset:21,endOffset:26,style:'underline',enabled:true},{type:'replace-text',blockId:text.id,text:'Completely different sentence'},{type:'fold-section',blockId:section.id,folded:true},{type:'resize-image',blockId:image.id,width:640},{type:'set-caption',blockId:figure.id,label:'Diagram',number:'3a',caption:'Memory topology'},{type:'set-caption',blockId:table.id,label:'Table',number:'2',caption:'Recorded value'},{type:'set-caption',blockId:video.id,label:'Video',number:'1',caption:'Playback overview'}]);
  expect(saved).toMatchObject({revision:1,title:'Renamed heading'});const effective=effectiveVersion(versionId)!,html=await readFile(effective.htmlPath,'utf8');expect(html.match(/<!doctype/gi)).toHaveLength(1);expect(html).toContain('data-afterdraft-section');expect(html).not.toMatch(/<details[^>]* open/);expect(html).toContain('data-afterdraft-caption-number=""');expect(html).toContain('Memory topology');expect(html).toContain('Recorded value');expect(html).toContain('width="640"');expect(html).toContain('width:640px!important;height:auto!important');expect(html).toContain('data-afterdraft-format="bold"');expect(html).toContain('data-afterdraft-format="italic"');expect(html).toContain('data-afterdraft-format="underline"');expect(html).toMatch(/<em><strong[^>]*>stable<\/strong><\/em>/);expect(html).toMatch(/<\/details><script/);expect(row<{title:string}>('SELECT title FROM documents WHERE id=?',imported.documentId)?.title).toBe('Renamed heading');expect(row<{status:string}>('SELECT status FROM anchors WHERE id=?',anchor)?.status).toBe('unmatched');expect(row<{body:string}>('SELECT body FROM search_index WHERE kind=\'article\' AND entity_id=?',versionId)?.body).toContain('Completely different sentence');expect(editHistory(versionId).currentRevision).toBe(1);
  await expect(saveEdits(versionId,0,[{type:'replace-text',blockId:heading.id,text:'Stale'}])).rejects.toMatchObject({statusCode:409});const restored=await restoreEdit(versionId,0,1);expect(restored).toMatchObject({revision:2,title:sourceTitle});const original=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8');expect(original).not.toContain('<details data-afterdraft-section');expect(original).not.toContain('Memory topology');expect(row<{title:string}>('SELECT title FROM documents WHERE id=?',imported.documentId)?.title).toBe(sourceTitle);expect(editHistory(versionId).revisions[0]).toMatchObject({revision:2,restored_from_revision:0});
})});

describe('academic final-touch document editing',()=>{
  it('changes semantic metadata and layout without flattening rich heading or caption markup',async()=>{
    const marker=randomUUID(),imported=await importSource({buffer:Buffer.from(`<title>Academic ${marker}</title><h1>Academic draft</h1><h2>Methods <em>and <strong>results</strong></em> <math><mi>x</mi></math></h2><p>Move destination</p><figure><img alt="Old alternative"><figcaption>Figure <strong>1</strong>. <math><mi>x</mi></math> response <a href="https://example.test/evidence">source</a></figcaption></figure><p>Tail</p><math display="block" alttext="Old equation"><semantics><mrow><mi>y</mi></mrow><annotation encoding="application/x-tex">y</annotation></semantics></math>`),filename:'academic.html',mimeType:'text/html'});if(!imported.versionId)throw new Error('Import failed');const versionId=imported.versionId;
    const heading=row<{id:string}>("SELECT id FROM blocks WHERE document_version_id=? AND text_content LIKE 'Methods%'",versionId)!,destination=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Move destination')!,figure=row<{id:string}>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='diagram'",versionId)!,image=row<{id:string}>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='image'",versionId)!,equation=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Old equation')!;
    const saved=await saveEdits(versionId,0,[{type:'set-heading-level',blockId:heading.id,level:3},{type:'set-alt-text',blockId:image.id,text:'A response curve with labelled axes'},{type:'set-alt-text',blockId:equation.id,text:'y equals the response variable'},{type:'set-caption',blockId:figure.id,label:'Diagram',number:'7',caption:'x response source'},{type:'set-object-layout',blockId:image.id,width:'full',alignment:'center',enlargeable:true,folded:true},{type:'move-object',blockId:image.id,destinationBlockId:destination.id,position:'after'}]);expect(saved.summary).toMatchObject({'set-heading-level':1,'set-alt-text':2,'set-caption':1,'set-object-layout':1,'move-object':1});
    const html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8'),$=cheerio.load(html),editedHeading=$(`[data-block-id="${heading.id}"]`),editedFigure=$(`[data-block-id="${figure.id}"]`),editedImage=$(`[data-block-id="${image.id}"]`),editedEquation=$(`[data-block-id="${equation.id}"]`),fold=editedFigure.parent('details[data-afterdraft-object-fold]');
    expect(editedHeading.is('h3')).toBe(true);expect(editedHeading.find('em>strong').text()).toBe('results');expect(editedHeading.find('math mi').text()).toBe('x');expect(editedImage.attr('alt')).toBe('A response curve with labelled axes');expect(editedEquation.attr('alttext')).toBe('y equals the response variable');expect(editedEquation.attr('aria-label')).toBe('y equals the response variable');expect(editedFigure.find('[data-afterdraft-caption-label]').text()).toBe('Diagram');expect(editedFigure.find('[data-afterdraft-caption-number]').text()).toBe('7');expect(editedFigure.find('[data-afterdraft-caption-text] math mi').text()).toBe('x');expect(editedFigure.find('[data-afterdraft-caption-text] a').attr('href')).toBe('https://example.test/evidence');expect(editedFigure.attr('data-afterdraft-layout-width')).toBe('full');expect(editedFigure.attr('data-afterdraft-layout-align')).toBe('center');expect(editedFigure.attr('data-afterdraft-enlargeable')).toBe('');expect(fold).toHaveLength(1);expect(fold.attr('open')).toBeUndefined();expect($(`[data-block-id="${destination.id}"]`).next().get(0)).toBe(fold.get(0));expect(row<{text_content:string}>('SELECT text_content FROM blocks WHERE id=?',equation.id)?.text_content).toBe('y equals the response variable');
    await expect(saveEdits(versionId,1,[{type:'set-caption',blockId:figure.id,label:'Diagram',number:'8',caption:'Flattened replacement'}])).rejects.toThrow('Structured caption body contains rich content');expect(editHistory(versionId).currentRevision).toBe(1);
  });

  it('moves and lays out a table with its scroll host, and adds fold chrome only while folded',async()=>{
    const marker=randomUUID(),imported=await importSource({buffer:Buffer.from(`<title>Table ${marker}</title><h1>Table draft</h1><table><caption>Measurements</caption><tr><th>Input</th><th>Output</th></tr><tr><td>A</td><td>B</td></tr></table><p>Place table here</p>`),filename:'table.html',mimeType:'text/html'});if(!imported.versionId)throw new Error('Import failed');const versionId=imported.versionId,table=row<{id:string}>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='table'",versionId)!,destination=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Place table here')!;
    await saveEdits(versionId,0,[{type:'set-object-layout',blockId:table.id,width:'content',alignment:'right',enlargeable:false,folded:false},{type:'move-object',blockId:table.id,destinationBlockId:destination.id,position:'after'}]);let html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8'),$=cheerio.load(html);const scroll=$(`[data-block-id="${table.id}"]`).closest('.afterdraft-table-scroll');expect($('body .afterdraft-table-scroll')).toHaveLength(1);expect(scroll.attr('data-afterdraft-layout-width')).toBe('content');expect(scroll.attr('data-afterdraft-layout-align')).toBe('right');expect(scroll.parent('details[data-afterdraft-object-fold]')).toHaveLength(0);expect($(`[data-block-id="${destination.id}"]`).next().get(0)).toBe(scroll.get(0));
    await saveEdits(versionId,1,[{type:'set-object-layout',blockId:table.id,width:'content',alignment:'right',enlargeable:false,folded:true}]);html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8');$=cheerio.load(html);expect($(`[data-block-id="${table.id}"]`).closest('details[data-afterdraft-object-fold]')).toHaveLength(1);
    await saveEdits(versionId,2,[{type:'set-object-layout',blockId:table.id,width:'content',alignment:'right',enlargeable:false,folded:false}]);html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8');$=cheerio.load(html);expect($('body details[data-afterdraft-object-fold]')).toHaveLength(0);expect($('body .afterdraft-table-scroll')).toHaveLength(1);
  });

  it('rejects semantic operations on the wrong block kinds and unsafe object moves',async()=>{
    const marker=randomUUID(),imported=await importSource({buffer:Buffer.from(`<title>Invalid ${marker}</title><h1>Invalid edits</h1><p>Ordinary text</p><figure><img alt="Object"><figcaption>Caption</figcaption></figure>`),filename:'invalid-academic.html',mimeType:'text/html'});if(!imported.versionId)throw new Error('Import failed');const versionId=imported.versionId,paragraph=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Ordinary text')!,image=row<{id:string}>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='image'",versionId)!;
    await expect(saveEdits(versionId,0,[{type:'set-alt-text',blockId:paragraph.id,text:'No'}])).rejects.toThrow('support alternative text');await expect(saveEdits(versionId,0,[{type:'set-heading-level',blockId:paragraph.id,level:3}])).rejects.toThrow('Only headings');await expect(saveEdits(versionId,0,[{type:'set-object-layout',blockId:paragraph.id,width:'auto',alignment:'left',enlargeable:false,folded:false}])).rejects.toThrow('support object layout');await expect(saveEdits(versionId,0,[{type:'move-object',blockId:paragraph.id,destinationBlockId:image.id,position:'after'}])).rejects.toThrow('can be moved');await expect(saveEdits(versionId,0,[{type:'move-object',blockId:image.id,destinationBlockId:image.id,position:'after'}])).rejects.toThrow('relative to itself');await expect(saveEdits(versionId,0,[{type:'move-object',blockId:image.id,destinationBlockId:'missing-block',position:'after'}])).rejects.toThrow('destination no longer exists');expect(editHistory(versionId).currentRevision).toBe(0);
  });
});

describe('Writer document editing',()=>{
  it('applies safe replace/insert/delete operations as one attributed revision',async()=>{
    const marker=randomUUID(),imported=await importSource({buffer:Buffer.from(`<title>Writer ${marker}</title><h1>Primary heading</h1><p>Old explanation</p><p>Duplicate paragraph</p><p>Media paragraph <img alt="Retained diagram"></p>`),filename:'writer.html',mimeType:'text/html'});if(!imported.versionId)throw new Error('Import failed');const versionId=imported.versionId;
    const old=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Old explanation')!,duplicate=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Duplicate paragraph')!,heading=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Primary heading')!,image=row<{id:string}>("SELECT id FROM blocks WHERE document_version_id=? AND block_type='image'",versionId)!;
    const operations:WriterEditOperation[]=[{type:'replace-text',blockId:old.id,text:'Revised explanation'},{type:'insert-text-block',blockId:old.id,position:'after',tag:'p',text:'Literal <script>alert(1)</script> explanation'},{type:'delete-text-block',blockId:duplicate.id}];
    const saved=await saveWriterEdits(versionId,0,operations,'proposal-safe');expect(saved).toMatchObject({revision:1,originType:'writer-proposal',originId:'proposal-safe'});
    const html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8');expect(html).toContain('Revised explanation');expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');expect(html).not.toContain('<script>alert(1)</script>');expect(html).not.toContain('Duplicate paragraph');expect(html).toContain('Retained diagram');
    expect(row<{origin_type:string;origin_id:string}>('SELECT origin_type,origin_id FROM document_edit_revisions WHERE document_version_id=? AND revision=1',versionId)).toEqual({origin_type:'writer-proposal',origin_id:'proposal-safe'});
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:old.id,text:'Again'}],'proposal-safe')).rejects.toMatchObject({statusCode:409});
    await expect(saveWriterEdits(versionId,1,[{type:'delete-text-block',blockId:heading.id}],'delete-heading')).rejects.toThrow('primary document heading');
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:heading.id,text:'   '}],'blank-heading')).rejects.toThrow('primary document heading');
    await expect(saveWriterEdits(versionId,1,[{type:'delete-text-block',blockId:image.id}],'delete-media')).rejects.toThrow('Only text blocks');
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:old.id,text:'Revised explanation'}],'noop')).rejects.toThrow('no-op');
    await expect(saveWriterEdits(versionId,1,[{type:'replace-text',blockId:old.id,text:'First'},{type:'replace-text',blockId:old.id,text:'Second'}],'conflict')).rejects.toThrow('more than once');
    expect(editHistory(versionId).currentRevision).toBe(1);
  });

  it('serializes competing revision writers and leaves one consistent winner',async()=>{
    const marker=randomUUID(),imported=await importSource({buffer:Buffer.from(`<title>Writer race ${marker}</title><h1>Race</h1><p>Original race text</p>`),filename:'race.html',mimeType:'text/html'});if(!imported.versionId)throw new Error('Import failed');const versionId=imported.versionId,block=row<{id:string}>('SELECT id FROM blocks WHERE document_version_id=? AND text_content=?',versionId,'Original race text')!;
    const results=await Promise.allSettled([saveWriterEdits(versionId,0,[{type:'replace-text',blockId:block.id,text:'Writer winner'}],'proposal-race'),saveEdits(versionId,0,[{type:'replace-text',blockId:block.id,text:'Manual winner'}])]);
    expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);const rejected=results.find(result=>result.status==='rejected') as PromiseRejectedResult;expect(rejected.reason).toMatchObject({statusCode:409});expect(editHistory(versionId).currentRevision).toBe(1);
    const html=await readFile(effectiveVersion(versionId)!.htmlPath,'utf8'),hasWriter=html.includes('Writer winner'),hasManual=html.includes('Manual winner');expect(hasWriter||hasManual).toBe(true);expect(hasWriter&&hasManual).toBe(false);
  });
});
